### ISSUE TITLE
Use of multiple frontends

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1013]
We have been seeing "odd" behavior of filesender when using multiple frontends to a shared backend (NFS). This issue is opened to document this behavior.

This always is with terasender turned on.

1. When using a DNS round-robin setup with 2 frontends, finalising a transfer or uploading a chunk frequently causes a retry with the message `{"terasend_worker_failed_to_start[exception... "the async request failed because it was aborted by some user action" ...] location: js frame :: https://my.filesender.url/js/terasender/terasender_worker.js :: <top level> :: line 14" data: no]}`. No specific logs are available at this point, but will follow later on.
2. When using a tcp load-balancer with 8 frontends in least-connections setup (in order to force selection of multiple backends), to attempt to reproduce this, whenever a chunk upload would end up in another frontend than the browser session is at, the upload stalls. When aborting the upload, the log shows:
```
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException exception uid:6086d06a62776] rest_bad_parameter
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException trace uid:6086d06a62776] #0 /opt/filesender/filesender-master-filesender-2.24/classes/rest/RestServer.class.php(305): RestEndpointTransfer->delete('undefined')
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException trace uid:6086d06a62776] #1 /opt/filesender/filesender-master-filesender-2.24/www/rest.php(37): RestServer::process()
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException trace uid:6086d06a62776] #2 {main}
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException details uid:6086d06a62776] method = "delete"
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException details uid:6086d06a62776] endpoint = "transfer"
[2021-04-26 15:38:34] [user 20] [rest:error] [user 20] [rest:error] [RestBadParameterException details uid:6086d06a62776] parameter = "transfer_id"
```
When scaling down both setups to a single frontend, they work like a charm.

Possibly this indicates an issue with state between multiple web frontends.

**Comment by kdermody** [comment]
I haven't tried a setup like this since around version 1.6, but certainly then for any setup with multiple webnodes required me to configure the load balancing with sticky sessions. Just having shared storage wasn't enough.

**Comment by WebSpider** [comment]
Yes. I've just tested this, and sticking sessions makes a lot of difference, thanks!
