### ISSUE TITLE
Missing MySQL privilege in Docs

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#106]
in filesender/docs/v2.0/install/index.md when creating the database and user the line 

`GRANT CREATE, ALTER, SELECT, INSERT, UPDATE, DELETE ON 'filesender'.* TO 'filesender'@'localhost';`

should now include 'INDEX' 

`GRANT CREATE, ALTER, SELECT, INSERT, INDEX, UPDATE, DELETE ON 'filesender'.* TO 'filesender'@'localhost';`

Otherwise initialising database in Step 8 will fail.

```
[2017-07-20 14:59:55] [upgrade:error] [8] Undefined variable: logger in /var/filesender/2.0/classes/utils/DatabaseMysql.class.php at line 112
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException exception uid:5970b75be21ef] database_access_failure
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #0 /var/filesender/2.0/classes/utils/DatabaseMysql.class.php(121): DBI::__callStatic('exec', Array)
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #1 /var/filesender/2.0/classes/utils/DatabaseMysql.class.php(121): DBI::exec('CREATE INDEX Au...')
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #2 [internal function]: DatabaseMysql::createTableSecondaryIndex('AuditLogs', 'AuditLogs_Type_...', Array, NULL)
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #3 /var/filesender/2.0/classes/utils/Database.class.php(104): call_user_func('DatabaseMysql::...', 'AuditLogs', 'AuditLogs_Type_...', Array, NULL)
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #4 /var/filesender/2.0/scripts/upgrade/database.php(123): Database::createTableSecondaryIndex('AuditLogs', 'AuditLogs_Type_...', Array)
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException trace uid:5970b75be21ef] #5 {main}
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef] "SQLSTATE[42000]: Syntax error or access violation: 1142 INDEX command denied to user 'filesender'@'localhost' for table 'AuditLogs'"
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef] Array
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef] (
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]     [name] => exec
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]     [args] => Array
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]         (
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]             [0] => CREATE INDEX AuditLogs_Type_ID on AuditLogs (target_type,target_id)
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]         )
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef] )
[2017-07-20 14:59:55] [upgrade:error] [DBIUsageException details uid:5970b75be21ef]
```

**Comment by monkeyiq** [comment]
Thanks for reporting this! PR 164 which is soon to be merged includes your change.

**Comment by monkeyiq** [comment]
merged
