### ISSUE TITLE
Log Facilities ConfigMissingParameterException

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#107]
When I manually configure the log_facilities option it complains of missing parameters, despite them being provided.

`
$config['log_facilities'] = array('type' => 'file', 'path' => '/path/to/lovely/files', 'rotate' => 'hourly');
`

```
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException exception uid:5971e281b3cd4] config_missing_parameter
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #0 /var/filesender/2.0/classes/utils/Logger.class.php(229): Logger::setup()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #1 /var/filesender/2.0/classes/utils/Logger.class.php(211): Logger::log('debug', 'Looking for cla...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #2 /var/filesender/2.0/classes/autoload.php(99): Logger::debug('Looking for cla...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #3 /var/filesender/2.0/classes/autoload.php(151): Autoloader::load('SimpleSAML_Auth...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #4 [internal function]: {closure}('SimpleSAML_Auth...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #5 /var/filesender/2.0/classes/auth/AuthSPSaml.class.php(207): spl_autoload_call('SimpleSAML_Auth...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #6 /var/filesender/2.0/classes/auth/AuthSPSaml.class.php(69): AuthSPSaml::loadSimpleSAML()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #7 [internal function]: AuthSPSaml::isAuthenticated()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #8 /var/filesender/2.0/classes/auth/AuthSP.class.php(55): call_user_func('AuthSPSaml::isA...')
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #9 /var/filesender/2.0/classes/auth/Auth.class.php(107): AuthSP::isAuthenticated()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #10 /var/filesender/2.0/classes/auth/Auth.class.php(190): Auth::user()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #11 /var/filesender/2.0/www/index.php(39): Auth::isAuthenticated()
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException trace uid:5971e281b3cd4] #12 {main}
Jul 21 12:16:17 goodly apache2: [gui:error] [ConfigMissingParameterException details uid:5971e281b3cd4] parameter = "log_facilities[type][path]"
```

**Comment by monkeyiq** [comment]
You need the second array() like the following. It is not so obvious so I have the code add info in the logs if it sees a log_facilities setting that only has the one array() in the setup. It was tempting to auto convert the setting, but that might run into other edge cases.

```
$config['log_facilities'] = 
  array(
    array(
        'type' => 'file', 
        'path' => '/path/to/lovely/files', 
        'rotate' => 'hourly'
    )
);
```
