### ISSUE TITLE
Guest voucher flow is broken when using service_aup

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1275]
## What am I doing

The filesender service is configured to have service_aup enabled, and normal aup disabled:
```
$config['aup_enabled'] = false;
$config['aup_default'] = false;       // AuP value is NOT already ticked
$config['service_aup_min_required_version'] = 5;
```
As an authenticated user, I send a voucher to an unknown (guest) user.

This guest user gets to the filesender URL, and then is presented with the servicewide AUP, which is all good.

## What happened

The user was unable to accept the servicewide AUP, the errormessage was:

**Authentication required**
You need to be authentified to do that. Maybe your session expired ? Please click Ok and authenticate again.

At this point, the guest voucher holder gets redirected to federated login, for which he has no credentials.

## What did I expect to happen
The user can agree to the AUP and proceed to the guest flow

## Details

Filesender version used: 2.32
Debug log:
```
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Guest.class.php:416 DBI::prepare(string(SELECT * FROM Guests WHERE token = :token)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Guest.class.php:417 (DBIStatement)->execute(array(:token => string(af38189e-d320-4efd-8a85-664f402f3905))) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/User.class.php:210 DBI::prepare(string(SELECT * FROM UserPreferences WHERE id = :id)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/User.class.php:211 (DBIStatement)->execute(array(:id => integer(1))) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/DBObject.class.php:748 DBI::prepare(string(UPDATE Guests SET userid = :userid, user_email = :user_email, token = :token, email = :email, transfer_count = :transfer_count, subject = :subject, message = :message, options = :options, transfer_options = :transfer_options, status = :status, created = :created, expires = :expires, last_activity = :last_activity, reminder_count = :reminder_count, last_reminder = :last_reminder, expiry_extensions = :expiry_extensions, service_aup_accepted_version = :service_aup_accepted_version, service_aup_accepted_time = :service_aup_accepted_time WHERE (id = :id))) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/DBObject.class.php:749 (DBIStatement)->execute(array(:id => integer(3), :userid => integer(1), :user_email => string(voucher_sender@ema.il), :token => string(af38189e-d320-4efd-8a85-664f402f3905), :email => string(voucher_receiver@ema.il), :transfer_count => integer(0), :subject => NULL, :message => NULL, :options => string({"valid_only_one_time":true,"does_not_expire":false,"email_guest_expired":false}), :transfer_options => string({"get_a_link":false}), :status => string(available), :created => string(2022-06-30 14:02:46), :expires => string(2022-07-14 00:00:00), :last_activity => string(2022-06-30 14:04:50), :reminder_count => integer(0), :last_reminder => string(1970-01-01 01:00:00), :expiry_extensions => integer(0), :service_aup_accepted_version => integer(0), :service_aup_accepted_time => NULL)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Authentication.class.php:116 DBI::prepare(string(SELECT * FROM Authentications WHERE id = :id)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Authentication.class.php:117 (DBIStatement)->execute(array(:id => integer(31))) DBI call
[2022-06-30 14:04:50] [rest:info] authentication::create(1) saml_uid XXX
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Authentication.class.php:137 DBI::prepare(string(SELECT * FROM Authentications WHERE saml_user_identification_uid = :samluid)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/Authentication.class.php:138 (DBIStatement)->execute(array(:samluid => string(XXX))) DBI call
[2022-06-30 14:04:50] [rest:info] authentication::create(2) FOUND AND RETURNING 31
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/User.class.php:281 DBI::prepare(string(SELECT * FROM UserPreferences WHERE authid = :authid)) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/data/User.class.php:282 (DBIStatement)->execute(array(:authid => integer(31))) DBI call
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/www/rest.php:37 RestServer::process() Got "put" request for endpoint "principal/" with 27 bytes payload
[2022-06-30 14:04:50] [rest:debug] /usr/share/filesender/filesender-2.30/classes/utils/Utilities.class.php:571 Utilities::getSecurityToken() Generated security token, value is 75a2a20e-021b-42b5-af19-1d3533b04045, valid until 2022-06-30 16:04:50
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException exception uid:62bd9162874c1] rest_xsrf_token_did_not_match
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException trace uid:62bd9162874c1] #0 /usr/share/filesender/filesender-2.30/www/rest.php(37): RestServer::process()
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException trace uid:62bd9162874c1] #1 {main}
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException details uid:62bd9162874c1] method = "put"
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException details uid:62bd9162874c1] endpoint = "principal"
[2022-06-30 14:04:50] [user 1] [rest:error] [RestException details uid:62bd9162874c1] "session token = 75a2a20e-021b-42b5-af19-1d3533b04045 and token = XXX"
```
and just to make sure with a brand new browser, no difference, xsrf failure again:

```
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException exception uid:62bd964732895] rest_xsrf_token_did_not_match
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException trace uid:62bd964732895] #0 /usr/share/filesender/filesender-2.30/www/rest.php(37): RestServer::process()
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException trace uid:62bd964732895] #1 {main}
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException details uid:62bd964732895] method = "put"
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException details uid:62bd964732895] endpoint = "principal"
[2022-06-30 14:25:43] [user 1] [rest:error] [RestException details uid:62bd964732895] "session token = d790b924-4686-4442-a085-7aefe2763030 and token = 3695cbcb-5446-45cd-a10a-0a274c82dd0e"
```

**Comment by WebSpider** [comment]
We currently have this working succesfully in 2.30, so this seems to be recently introduced

**Comment by WebSpider** [comment]
Update: Sometimes, looks can be deceiving. This was one of those cases. It turns out, that with certain cookie names and recently posted IETF drafts, the cookie that filesender is sending, does not get installed. I will open a seperate issue for this.
