### ISSUE TITLE
filesender.py http error 403

### ISSUE THREAD

**Issue by kyaky** [filesender/filesender#1318]
Hi Team,

I get this error when I use filesender.py. I've tried different setup with apache and nginx but none of them working with filesender.py.

please advise.

[root@syd01 ~]# ./sender.py -v -p -r email@gmail.com test.txt
base_url          : https://sender.test.test/rest.php
username          : admin
apikey            : 123123123
upload_chunk_size : 5242880 bytes
recipients        : email@gmail.com
files             : test.txt
insecure          : False
postTransfer
Traceback (most recent call last):
  File "./sender.py", line 307, in <module>
    options=troptions)['created']
  File "./sender.py", line 235, in postTransfer
    {}
  File "./sender.py", line 200, in call
    raise Exception('Http error '+str(code)+' '+response.text)
Exception: Http error 403 {"message":"rest_authentication_required","uid":"6322169da2123","details":{"method":"post","endpoint":"transfer"}}

I'm using "example-userpass" as auth backend.

Thanks

**Comment by WebSpider** [comment]
Quite possibly you are authenticating incorrectly.

The filesender logs should show you a hint as to what went wrong, but usually this means you have not set up a user API key, or registered the application in the filesender config.

Setting up user API keys is done in the user profile section of the webinterface
Setting up a registered application in the filesender config is done via the `auth_remote_applications` directive.

**Comment by kyaky** [comment]
Thanks for the reply.

I believe I used the correct API as:
 when I intentionally used wrong API, the filesender.py returns 500:
_Exception: Http error 500 {"message":"auth_remote_signature_check_failed","uid":"6327f37d41195","details":null}_

When I switched to correct API showed in the database, it returned 403:
_Exception: Http error 403 {"message":"rest_authentication_required","uid":"6327f3c1abac0","details":{"method":"post","endpoint":"transfer"}}_

This is my setup enviroment,

1. I'm use "example-userpass" set up in simplesaml
2. I've checked the AARNET UI backend. My setup UI doesn't have secret info neither the delete / create API secret buttons. screenshot attached
Mine
![image](https://user-images.githubusercontent.com/5505790/190951304-346c6163-4169-4ae1-80ff-92e630439f28.png)
ARRNET
![image](https://user-images.githubusercontent.com/5505790/190951265-0c7f8561-3b15-4231-8d00-8475d5b4f0fa.png)
3. However in database there is an API which I'm using
![image](https://user-images.githubusercontent.com/5505790/190951019-0d9011e8-202d-4736-87a2-905d4a2c17d0.png)

1. Does Filesender UI broken when auth is using "example-userpass" local auth?
2. my log doesn't show any error when filesender.py returns error 403

[2022-09-19 05:49:28] [rest:info] authentication::create(1) saml_uid admin
[2022-09-19 05:49:28] [rest:info] authentication::create(2) FOUND AND RETURNING 15
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException exception uid:6327f4d884b17] rest_authentication_required
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException trace uid:6327f4d884b17] #0 /home/admin/domains/sender.test.com/public_html/classes/rest/RestServer.class.php(305): RestEndpointTransfer->post()
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException trace uid:6327f4d884b17] #1 /home/admin/domains/sender.test.com/public_html/www/rest.php(37): RestServer::process()
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException trace uid:6327f4d884b17] #2 {main}
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException details uid:6327f4d884b17] method = "post"
[2022-09-19 05:49:28] [rest:error] [RestAuthenticationRequiredException details uid:6327f4d884b17] endpoint = "transfer"

**Comment by kyaky** [comment]
Someone help me find the problem that "auth_remote_user_enabled" is not enabled in config file.

This is not recorded in https://docs.filesender.org/filesender/v2.0/admin/configuration/

**Comment by WebSpider** [comment]
Thanks for pointing this out, I'll send in a request to add this to the documentation

**Comment by kyaky** [comment]
1318 is fixed  but 1324 has nothing to do with this one.
