### ISSUE TITLE
Cron: Guest and guest-transfer expiry

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1326]
When a guest has a shorter lifetime than the maximum transfer validity, or when changing these values in a running production environment, a guest can get expired before it's transfers are expired. This causes their transfers to never expire because of a missing relationship in the database.

The current code that expires the guest is here: https://github.com/filesender/filesender/blob/fdf12ec4d657d16e3feb1dd7a24d99b87ab43273/scripts/task/cron.php#L79

This is causing errors like these in cron log:

```
$ grep cron ./filesender_2022-09-*|grep "Guest#12896"
./filesender_2022-09-03_03h.log:[2022-09-03 03:00:09] [cron:info] Guest#12896(XXX@XXX) expired and before guests_expired_lifetime so deleting it

$ grep GuestNotFoundException ./filesender_2022-09-*|grep "cron.error"|grep selector
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException details uid:6317fb23570f9] selector = "id = 12896"
./filesender_2022-09-08_03h.log:[2022-09-08 03:00:26] [cron:error] [GuestNotFoundException details uid:63194cbaddac1] selector = "id = 12993"
./filesender_2022-09-09_03h.log:[2022-09-09 03:00:11] [cron:error] [GuestNotFoundException details uid:631a9e2ba995c] selector = "id = 12896"
./filesender_2022-09-10_03h.log:[2022-09-10 03:00:09] [cron:error] [GuestNotFoundException details uid:631befa9103e4] selector = "id = 12896"
./filesender_2022-09-11_03h.log:[2022-09-11 03:00:15] [cron:error] [GuestNotFoundException details uid:631d412f232ed] selector = "id = 12896"
```

And their transfers to fail expiry, causing unwanted storage buildup, still having data when we promised to delete it, etc:

```
$ grep GuestNotFoundException ./filesender_2022-09-07* | grep "cron.error"
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException exception uid:6317fb23570f9] guest_not_found
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #0 /usr/local/filesender/filesender/classes/data/DBObject.class.php(759): Guest->__construct('12896', false)
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #1 /usr/local/filesender/filesender/classes/data/DBObject.class.php(191): DBObject::createFactory('12896')
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #2 /usr/local/filesender/filesender/classes/data/AuditLog.class.php(293): DBObject::fromId('12896')
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #3 /usr/local/filesender/filesender/templates/report_plain.php(15): AuditLog->__get('author')
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #4 /usr/local/filesender/filesender/classes/utils/Template.class.php(117): include('/usr/local/file...')
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #5 /usr/local/filesender/filesender/classes/utils/Template.class.php(124): Template::{closure}('/usr/local/file...', Array)
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #6 /usr/local/filesender/filesender/classes/utils/Report.class.php(176): Template::process('report_plain', Array)
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #7 /usr/local/filesender/filesender/classes/data/Transfer.class.php(759): Report->sendTo(Object(User))
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #8 /usr/local/filesender/filesender/scripts/task/cron.php(65): Transfer->close(false)
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException trace uid:6317fb23570f9] #9 {main}
./filesender_2022-09-07_03h.log:[2022-09-07 03:00:03] [cron:error] [GuestNotFoundException details uid:6317fb23570f9] selector = "id = 12896"
```

```
filesender=> select id,user_email from guests where id=12896;
 id | user_email 
----+------------
(0 rows)

filesender=> select expires from transfers where guest_id=12896 order by expires;

       expires       
---------------------
 2022-09-06 23:00:00
 2022-09-07 23:00:00
 2022-09-07 23:00:00
 2022-09-07 23:00:00
 2022-09-07 23:00:00
 2022-09-08 23:00:00
 2022-09-08 23:00:00
 2022-09-08 23:00:00
 2022-09-08 23:00:00
```

Since the  guest is able to select the expiry date of the transfer themselves, we should honor this. It would make sense to disable the guest once it's voucher is expired, instead of deleting it from the database, and only delete it, once it's last transfer has been cleaned up.

**Comment by madsi1m** [comment]
We are also seeing this issue

**Comment by madsi1m** [comment]
from our logs

```
{
  "message": "[GuestNotFoundException exception uid:637579d3a1a88] guest_not_found",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #0 /www/filesender/classes/data/DBObject.class.php(759): Guest->__construct('262500', false)",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #1 /www/filesender/classes/data/DBObject.class.php(191): DBObject::createFactory('262500')",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #2 /www/filesender/classes/data/AuditLog.class.php(293): DBObject::fromId('262500')",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #3 /www/filesender/templates/report_plain.php(15): AuditLog->__get('author')",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #4 /www/filesender/classes/utils/Template.class.php(117): include('/www/...')",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #5 /www/filesender/classes/utils/Template.class.php(124): Template::{closure}('/www/...', Array)",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #6 /www/filesender/classes/utils/Report.class.php(176): Template::process('report_plain', Array)",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #7 /www/filesender/classes/data/Transfer.class.php(759): Report->sendTo(Object(User))",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #8 /www/filesender/scripts/task/cron.php(65): Transfer->close(false)",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException trace uid:637579d3a1a88] #9 {main}",
  "time": 1668643283
}
{
  "message": "[GuestNotFoundException details uid:637579d3a1a88] selector = \"id = 262500\"",
  "time": 1668643283
}
```

**Comment by monkeyiq** [comment]
The `--force` option I added to cron.php in https://github.com/filesender/filesender/pull/1352 will also ignore errors sending reports during transfer delete. Given the above backtrace this should allow Transfers that should be deleted (expired etc) to be deleted even if the guest tuple is already gone in the system.

**Comment by monkeyiq** [comment]
Please reopen the issue if it is still present for you. Thank you for reporting this!
