### ISSUE TITLE
Issue with guest uploads with Cloud Backend S3

### ISSUE THREAD

**Issue by flowdnb** [filesender/filesender#1411]
Hello,

We are facing an issue with v2.39 when using guest uploads while the file store is connected to an S3-compatible cloud backend (IBM Cloud Object Storage on-premises).

- Configuration we have is:
```
$config['storage_type']      = 'CloudS3';
$config['cloud_s3_endpoint'] = 'https://MyHiddenS3Endpoint.local';
$config['cloud_s3_key']      = 'MyHiddenS3Key';
$config['cloud_s3_secret']   = 'MyHiddenS3Secret';
$config['cloud_s3_bucket']   = 'MyHiddenS3Bucket';
```

- FileSender tries to create a bucket for the file uploaded by guests instead of putting it into the configured bucket (at the same time, uploads work for authenticated users).

```
exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "CreateBucket" on "https://MyHiddenS3Endpoint.local/6c556b43-73a8-47dd-b086-65884b0df4b7"; AWS HTTP error: Client error: `PUT https://MyHiddenS3Endpoint.local/6c556b43-73a8-47dd-b086-65884b0df4b7` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>AccessDenied</Code><Message>The provided account is  (truncated...)
 AccessDenied (client): The provided account is not authorized to create vaults through the Provisioning API - <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>AccessDenied</Code><Message>The provided account is not authorized to create vaults through the Provisioning API</Message><Resource>/6c556b43-73a8-47dd-b086-65884b0df4b7/</Resource><RequestId>669a5787-685d-441c-be2b-e2afcce3707c</RequestId><httpStatusCode>403</httpStatusCode></Error>'

GuzzleHttp\Exception\ClientException: Client error: `PUT https://MyHiddenS3Endpoint.local/6c556b43-73a8-47dd-b086-65884b0df4b7` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>AccessDenied</Code><Message>The provided account is  (truncated...)
 in /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\Promise\TaskQueue->run()
#5 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(184): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
#7 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 /opt/filesender/filesender/optional-dependencies/s3/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /opt/filesender/filesender/optional-dependencies/s3/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#14 /opt/filesender/filesender/optional-dependencies/s3/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute()
#15 /opt/filesender/filesender/classes/storage/StorageCloudS3.class.php(175): Aws\AwsClient->__call()
#16 /opt/filesender/filesender/classes/storage/Storage.class.php(207): StorageCloudS3::writeChunk()
#17 /opt/filesender/filesender/classes/data/File.class.php(449): Storage::writeChunk()
#18 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointFile.class.php(531): File->writeChunk()
#19 /opt/filesender/filesender/classes/rest/RestServer.class.php(299): RestEndpointFile->put()
#20 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
#21 {main}
```

- To narrow down the problem, we had to include the exception's content in **StorageCloudS3.class.php** function *writeChunk()*:
`$msg = 'S3: writeChunk() Can not write to object_name: ' . $object_name . ' offset ' . $offset . '(Exception: ' . $e . ')';`
  - Before it logged only
`[user 16] [rest:error] [StorageFilesystemCannotWriteException details uid:6418d0341ce39] path = "S3: writeChunk() Can not write to object_name: 000000000000000000000000 offset 0")`
and
`[user 16] [rest:info] S3: writeChunk() Can not write to object_name: 000000000000000000000000 offset 0(Exception: InvalidArgumentException: Found 1 error while validating the input provided for the PutObject operation:
[Bucket] is missing and is a required parameter in /opt/filesender/filesender/optional-dependencies/s3/vendor/aws/aws-sdk-php/src/Api/Validator.php:65`.

- If we hard code the bucket, the problem does not occur and the guest upload works as expected.
```
public static function getBucketName(File $file)
    {
        if( self::usingCustomBucketName( $file ) ) {
            return $file->transfer->options[TransferOptions::STORAGE_CLOUD_S3_BUCKET];
        }
        // return $file->uid;
        return 'MyHiddenS3Bucket';
    }
```
Thank you for any help in solving this issue or for any hints on a configuration error.

**Comment by monkeyiq** [comment]
I have merged https://github.com/filesender/filesender/pull/1416. Thank you for the fix!
