### ISSUE TITLE
Using 'db_table_prefix' causes initial db setup to fail

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1543]
When using the config parameter `$config['db_table_prefix'] ='test';` to specify a table prefix, the initial database setup fails with the following error:
```
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException exception uid:6500733086aca] database_access_failure
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException trace uid:6500733086aca] #0 /opt/filesender/filesender-feature-new-ui/classes/utils/DatabaseMysql.class.php(86): DBI::__callStatic()
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException trace uid:6500733086aca] #1 /opt/filesender/filesender-feature-new-ui/classes/utils/Database.class.php(178): DatabaseMysql::createView()
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException trace uid:6500733086aca] #2 /opt/filesender/filesender-feature-new-ui/scripts/upgrade/database.php(738): Database::createView()
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException trace uid:6500733086aca] #3 {main}
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca] "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'filesender.DBConstantEpochTypes' doesn't exist"
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca] Array
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca] (
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]     [name] => exec
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]     [args] => Array
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]         (
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]             [0] => CREATE OR REPLACE VIEW fs3_aggregatestatisticsview as select agg.*, sizesum/eventcount as sizemean , timesum/eventcount as timemean , DBConstantEpochTypes.description  as epochtypetext , DBConstantStatsEvents.description as eventtypetext   from fs3_AggregateStatistics agg join DBConstantEpochTypes  on DBConstantEpochTypes.id=agg.epochtype  join DBConstantStatsEvents on DBConstantStatsEvents.id=agg.eventtype
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]         )
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca] )
[2023-09-12 16:18:24] [upgrade:error] [DBIUsageException details uid:6500733086aca]
```

It would seem the prefix isnt consistently applied to all tables/views.
Setting the prefix to '' (empty) lets the install succeed.

**Comment by monkeyiq** [comment]
I wonder if the option might be better to be removed. I think this bug has been around for a while and unnoticed as the prefix has not been used.

**Comment by WebSpider** [comment]
I think upgrades also do not work correctly now, since they use the same database management, right?

If so, I would have no problem deprecating the feature, and removing it in 3.x

**Comment by monkeyiq** [comment]
I have marked this as deprecated in 2.41+ and earmarked for removal in 3.x.

**Comment by monkeyiq** [comment]
I guess fix merged as fix == deprecation.
