### ISSUE TITLE
storage_filesystem_bad_usage_output for storage_filesystem_hashing

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#177]
When I enable storage_filesystem_hashing I get the following error

	[2017-11-07 11:16:49] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException exception uid:5a019621d46a5] storage_filesystem_bad_usage_output
	[2017-11-07 11:16:49] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #0 /var/filesender/2.0-beta2/classes/storage/StorageFilesystem.class.php(126): StorageFilesystem::getFilesystem('/ceph/filesende...')
	[2017-11-07 11:16:49] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #1 [internal function]: StorageFilesystem::canStore(Object(Transfer))
	[2017-11-07 11:16:49] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #2 /var/filesender/2.0-beta2/classes/storage/Storage.class.php(111): call_user_func('StorageFilesyst...', Object(Transfer))
	[2017-11-07 11:16:49] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #3 /var/filesender/2.0-beta2/classes/rest/endpoints/RestEndpointTransfer.class.php(497): Storage::canStore(Object(Transfer))
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #4 [internal function]: RestEndpointTransfer->post()
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #5 /var/filesender/2.0-beta2/classes/rest/RestServer.class.php(259): call_user_func_array(Array, Array)
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #6 /var/filesender/2.0-beta2/www/rest.php(37): RestServer::process()
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019621d46a5] #7 {main}
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException details uid:5a019621d46a5] cmd = "df '/ceph/filesender/2.0/beta2/files/'"
	[2017-11-07 11:16:50] [rest:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException details uid:5a019621d46a5] line = "193.1.XX.XX:/nfs/multimedia/filesender 102397913088 66963936128 35433976960  66% /ceph/filesender"

Turning on storage_filesystem_ignore_disk_full_check clears the issue. 

For info, my storage is over NFS

	193.1.XX.XX:/nfs/multimedia/filesender /ceph/filesender nfs auto,_netdev,rw,nfsvers=3,tcp,rsize=131072,wsize=131072,hard,intr 0 0

OS is Ubuntu 14.04

filesender-2.0-beta2

**Comment by monkeyiq** [comment]
I have just merged https://github.com/filesender/filesender/pull/201  which should stop this issue from happening.

If you are still getting the bad_usage_output then it might be useful to see the output of running the following there is I can update the code. Hopefully the testing with NFS I have done here on Fedora 27 will mean your setup is also going to work.

```
df /ceph/filesender/2.0/beta2/files
```
