### ISSUE TITLE
storage_filesystem_bad_resolver_target on Admin page

### ISSUE THREAD

**Issue by kdermody** [filesender/filesender#178]
When I turn on storage_filesystem_hashing I get the following error when I attempt to access the Admin page

(the hashing works for users uploading files)

	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException exception uid:5a0199d40da80] storage_filesystem_bad_resolver_target
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #0 /var/filesender/2.0-beta2/classes/storage/StorageFilesystem.class.php(214): StorageFilesystem::getFilesystem('/ceph/filesende...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #1 [internal function]: StorageFilesystem::getUsage()
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #2 /var/filesender/2.0-beta2/classes/storage/Storage.class.php(124): call_user_func('StorageFilesyst...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #3 /var/filesender/2.0-beta2/templates/admin_statistics_section.php(27): Storage::getUsage()
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #4 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #5 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #6 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('admin_statistic...', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #7 /var/filesender/2.0-beta2/templates/admin_page.php(30): Template::display('admin_statistic...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #8 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #9 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #10 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('admin_page', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #11 /var/filesender/2.0-beta2/templates/page.php(9): Template::display('admin_page', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #12 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #13 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #14 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('page', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #15 /var/filesender/2.0-beta2/www/index.php(59): Template::display('page', Array)
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException trace uid:5a0199d40da80] #16 {main}
	[2017-11-07 11:32:36] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverTargetException details uid:5a0199d40da80] what = "/ceph/filesender/2.0/beta2/files/0"

It appears to be looking for a directory which has not yet been created. If I manually create the directories I get the following error.

	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException exception uid:5a019a385ce74] storage_filesystem_bad_usage_output
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #0 /var/filesender/2.0-beta2/classes/storage/StorageFilesystem.class.php(214): StorageFilesystem::getFilesystem('/ceph/filesende...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #1 [internal function]: StorageFilesystem::getUsage()
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #2 /var/filesender/2.0-beta2/classes/storage/Storage.class.php(124): call_user_func('StorageFilesyst...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #3 /var/filesender/2.0-beta2/templates/admin_statistics_section.php(27): Storage::getUsage()
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #4 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #5 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #6 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('admin_statistic...', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #7 /var/filesender/2.0-beta2/templates/admin_page.php(30): Template::display('admin_statistic...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #8 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #9 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #10 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('admin_page', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #11 /var/filesender/2.0-beta2/templates/page.php(9): Template::display('admin_page', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #12 /var/filesender/2.0-beta2/classes/utils/Template.class.php(90): include('/var/filesender...')
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #13 /var/filesender/2.0-beta2/classes/utils/Template.class.php(97): Template::{closure}('/var/filesender...', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #14 /var/filesender/2.0-beta2/classes/utils/Template.class.php(184): Template::process('page', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #15 /var/filesender/2.0-beta2/www/index.php(59): Template::display('page', Array)
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException trace uid:5a019a385ce74] #16 {main}
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException details uid:5a019a385ce74] cmd = "df '/ceph/filesender/2.0/beta2/files/0'"
	[2017-11-07 11:34:16] [gui:error] [user kdermody@heanet.ie] [StorageFilesystemBadResolverOutputException details uid:5a019a385ce74] line = "193.1.XX.XX:/nfs/multimedia/filesender 102397913088 66965124992 35432788096  66% /ceph/filesender"

For info, my storage is over NFS

	193.1.XX.XX:/nfs/multimedia/filesender /ceph/filesender nfs auto,_netdev,rw,nfsvers=3,tcp,rsize=131072,wsize=131072,hard,intr 0 0

OS is Ubuntu 14.04

filesender-2.0-beta2

**Comment by monkeyiq** [comment]
I'm going to test with the following as I assume it is a somewhat common setting when enabling hashing:
```
storage_filesystem_hashing=2
```

please let me know if you are using a callable or other setting so I can try that too :)

**Comment by monkeyiq** [comment]
ok, I am also getting storage_filesystem_bad_resolver_target on the admin page. I'll move to fix that up.

If I create that directory then the code moves on to look for another directory. So the second issue with storage_filesystem_bad_usage_output might be a second thing to fix. What output do you get from running the following:
```
df '/ceph/filesender/2.0/beta2/files/0'
```

For me I get something like the following
```
# df /opt/filesender/files/0
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        61G   18G   42G  31% /var
```

**Comment by monkeyiq** [comment]
digging into the code I think I see why you get storage_filesystem_bad_usage_output, so no need to do the df above.

**Comment by monkeyiq** [comment]
https://github.com/filesender/filesender/pull/201 should stop filesender from looking for directories that have not been created yet.

it should also resolve the issue that was causing storage_filesystem_bad_usage_output for you. It might be better to handle that exception in https://github.com/filesender/filesender/issues/177 if it is still happening after https://github.com/filesender/filesender/pull/201 is merged.
