### ISSUE TITLE
missing translation, generates an exception

### ISSUE THREAD

**Issue by StCyr** [filesender/filesender#1818]
one of our customer doesn't release the email attribute, it creates an exception:

```
Mar 11 14:44:15 fedsender simplesamlphp[612442]: PHP Warning:  Undefined variable $tr in /opt/filesender-2.41/classes/utils/Lang.class.php on line 482
Mar 11 14:44:15 fedsender simplesamlphp[612442]: PHP Warning:  Trying to access array offset on value of type null in /opt/filesender-2.41/classes/utils/Lang.class.php on line 482
Mar 11 14:44:15 fedsender simplesamlphp[612442]: PHP Warning:  Undefined variable $tr in /opt/filesender-2.41/classes/utils/Lang.class.php on line 482
Mar 11 14:44:15 fedsender simplesamlphp[612442]: PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /opt/filesender-2.41/classes/utils/Lang.class.php:482
Mar 11 14:44:15 fedsender simplesamlphp[612442]: Stack trace:
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #0 /opt/filesender-2.41/classes/utils/Lang.class.php(530): Lang::translate()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #1 /opt/filesender-2.41/classes/exceptions/AuthSPExceptions.class.php(92): Lang::tr()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #2 /opt/filesender-2.41/classes/auth/AuthSPSaml.class.php(148): AuthSPMissingAttributeException->__construct()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #3 /opt/filesender-2.41/classes/auth/AuthSP.class.php(70): AuthSPSaml::attributes()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #4 /opt/filesender-2.41/classes/auth/Auth.class.php(171): AuthSP::attributes()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #5 /opt/filesender-2.41/classes/auth/Auth.class.php(279): Auth::user_protected()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #6 /opt/filesender-2.41/classes/auth/Auth.class.php(341): Auth::user()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #7 /opt/filesender-2.41/classes/utils/Config.class.php(169): Auth::isAuthenticated()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #8 /opt/filesender-2.41/classes/utils/Config.class.php(479): Config::load()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #9 /opt/filesender-2.41/includes/init.php(43): Config::get()
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #10 /opt/filesender-2.41/www/index.php(34): require_once('...')
Mar 11 14:44:15 fedsender simplesamlphp[612442]: #11 {main}
Mar 11 14:44:15 fedsender simplesamlphp[612442]:   thrown in /opt/filesender-2.41/classes/utils/Lang.class.php on line 482
```

I think the Lang class is looking for string with id `auth_sp_attribute_email_hint` which doesn't exist

**Comment by monkeyiq** [comment]
I am not sure if you have access to the site the customer is using. If so the patch in https://github.com/filesender/filesender/pull/1819 will log the translation id that is causing the issue and may try to continue (I say may because I haven't tested what happens there).

I will likely write a test case for this and if it proceeds successfully then merge the PR. It is probably nicer to see just the untranslated string on the rare occasion than to stop the entire process.

**Comment by monkeyiq** [comment]
Thank you for the report. The system should generate better logs now too and a specific merge for the missing translation was added in https://github.com/filesender/filesender/pull/1825.

**Comment by monkeyiq** [comment]
please reopen or report again if this or other missing translations cause undesired outcomes.
