### ISSUE TITLE
log file flooded with AuthRemoteSignatureCheckFailedException exceptions

### ISSUE THREAD

**Issue by StCyr** [filesender/filesender#1840]
It seems someone is trying to use Remote User REST API authentication against our instance for a few days and our logs are flooded with stack traces due to AuthRemoteSignatureCheckFailedException exceptions

```
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: Stack trace:
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #0 /opt/filesender-2.41/classes/auth/Auth.class.php(149): AuthRemote::isAuthenticated()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #1 /opt/filesender-2.41/classes/auth/Auth.class.php(279): Auth::user_protected()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #2 /opt/filesender-2.41/classes/auth/Auth.class.php(341): Auth::user()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #3 /opt/filesender-2.41/classes/utils/Config.class.php(169): Auth::isAuthenticated()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #4 /opt/filesender-2.41/classes/utils/Config.class.php(479): Config::load()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #5 /opt/filesender-2.41/includes/init.php(43): Config::get()
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #6 /opt/filesender-2.41/www/rest.php(33): require_once('...')
Mar 26 11:05:39 fedsender simplesamlphp[1103049]: #7 {main}
Mar 26 11:05:39 fedsender simplesamlphp[1103049]:   thrown in /opt/filesender-2.41/classes/auth/AuthRemote.class.php on line 159
```

I'll try to contact the person trying to use our API but I don't find it a good idea to throw an exception in this case (and flood our logs). Shouldn't rather the exception be properly handled in the code?

From what I can see in the code, the Auth::isAuthenticated() function has a parameter to either throw the exception or return false, but in this case this function is called with this parameter sets so that it will thrown the exception rather than returning false.

This function is called from Config::load():

```php
        // Load config regex overrides if used and present
        $auth_config_regex_files = self::get('auth_config_regex_files');
        if( !empty($auth_config_regex_files) && is_array($auth_config_regex_files) && Auth::isAuthenticated()) {
                $auth_attrs = Auth::attributes();
                foreach ($auth_config_regex_files as $attr=>$regex_and_configs) {
                        if (!is_array($regex_and_configs)) {
                                continue;
                        }
                        foreach ($regex_and_configs as $regex => $extra_config_name) {
                                if (preg_match('`'.$regex.'`', $auth_attrs[$attr])) {
                                        $extra_config_file = FILESENDER_BASE.'/config/config-' . $extra_config_name . '.php';
                                        if (file_exists($extra_config_file)) {
                                                $config = array();
                                                include_once($extra_config_file);
                                                self::merge(self::$parameters, $config);
                                        }
                                }
                        }
                }
        }
```

I think the `Auth::isAuthenticated()` could be called with the `critical=false` argument:

```php
        // Load config regex overrides if used and present
        $auth_config_regex_files = self::get('auth_config_regex_files');
---        if( !empty($auth_config_regex_files) && is_array($auth_config_regex_files) && Auth::isAuthenticated()) {
+++        if( !empty($auth_config_regex_files) && is_array($auth_config_regex_files) && Auth::isAuthenticated(false)) {
                $auth_attrs = Auth::attributes();
                foreach ($auth_config_regex_files as $attr=>$regex_and_configs) {
                        if (!is_array($regex_and_configs)) {
                                continue;
                        }
                        foreach ($regex_and_configs as $regex => $extra_config_name) {
                                if (preg_match('`'.$regex.'`', $auth_attrs[$attr])) {
                                        $extra_config_file = FILESENDER_BASE.'/config/config-' . $extra_config_name . '.php';
                                        if (file_exists($extra_config_file)) {
                                                $config = array();
                                                include_once($extra_config_file);
                                                self::merge(self::$parameters, $config);
                                        }
                                }
                        }
                }
        }
```

It would just make filesender skip some customisation when the user is not authenticated.

**Comment by monkeyiq** [comment]
The `critical` argument to `isAuthenticated` controls if an exception is thrown or false is returned:
https://github.com/filesender/filesender/blob/fa78ddee1e9b9037264e5736b87ded1198eb2d41/classes/auth/Auth.class.php#L329

Either way the exception will still be thrown further down the call chain. 
https://github.com/filesender/filesender/blob/fa78ddee1e9b9037264e5736b87ded1198eb2d41/classes/auth/AuthRemote.class.php#L159

It is just that `isAuthenticated` will catch an exception and return `false` for non `critical` calls. Either way the exception logging will still be done.

As each exception has a class name as well as a specific message-id, such as auth_remote_signature_check_failed in this case it might make sense to be able to present a list or regex of exceptions that a site might wish to ignore. This would be an opposite of sorts to the existing  `exception_additional_logging_regex` option.

**Comment by StCyr** [comment]
oh, sorry my pasting of the logs wasn't complete:

```
Mar 27 13:39:46 fedsender simplesamlphp[1135093]: PHP Fatal error:  Uncaught AuthRemoteSignatureCheckFailedException: auth_remote_signature_check_failed in /opt/filesender-2.41/classes/auth/AuthRemote.class.php:159
Mar 27 13:39:46 fedsender simplesamlphp[1135093]: Stack trace:
Mar 27 13:39:46 fedsender simplesamlphp[1135093]: #0 /opt/filesender-2.41/classes/auth/Auth.class.php(149): AuthRemote::isAuthenticated()
M...
```

This logging wouldn't be done should isAuthenticated be called with critical=false since the exception would be caught.

**Comment by monkeyiq** [comment]
The logging is done in the base exception class constructor. Inside LoggingException constructor to be exact.

LoggingException extends Exception
DetailedException extends LoggingException
AuthRemoteSignatureCheckFailedException extends DetailedException

The DetailedException will populate the 'trace' element with a backtrace and in the LoggingException constructor that is passed to `$this->log` which in turn ends up at `Logger::error`
https://github.com/filesender/filesender/blob/b0ba2794c21116029174ddaf838271af790b0550/classes/exceptions/Exceptions.class.php#L79

So the exception being thrown will generate the logging. I have a new PR up that allows you to nominate an array of exception classes that should not be logged this way https://github.com/filesender/filesender/pull/1843. This should allow precise control over nuisance exceptions clogging up the log files at the expense of not knowing if these things are happening.

**Comment by StCyr** [comment]
hmmm, I see what you mean: the exception will be logged in `config['log_facilities']`. 

I was not actually looking at these files but rather to `/var/log/syslog` where the trace isn't logged with `critical=false`

**Comment by monkeyiq** [comment]
I should clarify which log file next time. On the upside we now also have ways to ignore exceptions in the `config['log_facilities']` logs as well ;) I just tested your update merged in https://github.com/filesender/filesender/pull/1848 above with a forced exception. With the `critical=false` my `/var/log/php-fpm/www-error.log` log file is less cluttered.

Thank you for the report and fix!

**Comment by monkeyiq** [comment]
This should be in yesterday's release.
