### ISSUE TITLE
Deleting a file from a transfer post upload breaks transfer page.

### ISSUE THREAD

**Issue by PaulLocksley** [filesender/filesender#1860]
### Versions tested:
- 2.47
- Dev3

### Steps to reproduce:

1. Create and send a new transfer of files 
     - I believe it requires a directory to be present, this did not happen when I upload the files without a directory in the path, but if I chose the upload directory option that includes the folder name the steps below work.
     - All transfers that had this error had 100+ files, I did not test fuly on smaller transfers.
     - All transfers were in "get a link" mode.
2. Navigate to "My Transfers".
3. Expand the transfer.
4. Delete a random file without closing the transfer.
5. Reload the page and observe error.
6. Optional, call /transfers and observe 500 error with no body text.

See images below:
#### 2.47
![image](https://github.com/filesender/filesender/assets/96610143/0ae1a870-a2d7-4ee0-9afb-52e851a6b195)
![image](https://github.com/filesender/filesender/assets/96610143/7cc1d16e-90f1-4005-8d1b-ff929a4bbbbb)

#### Dev3
![image](https://github.com/filesender/filesender/assets/96610143/0ce97cfb-a411-412a-b2fc-c8803d66810d)

**Comment by PaulLocksley** [comment]
Php error logs:
```[09-Apr-2024 08:01:04 Europe/London] PHP Warning:  Undefined array key 183 in /opt/filesender/filesender/classes/data/File.class.php on line 429
[09-Apr-2024 08:01:04 Europe/London] PHP Warning:  Attempt to read property "name" on null in /opt/filesender/filesender/classes/data/File.class.php on line 430
[09-Apr-2024 08:01:04 Europe/London] PHP Fatal error:  Uncaught Error: Attempt to assign property "pathCache" on null in /opt/filesender/filesender/classes/data/File.class.php:430
Stack trace:
#0 /opt/filesender/filesender/classes/data/Transfer.class.php(1084): File::fromTransfer()
#1 /opt/filesender/filesender/classes/data/Transfer.class.php(1109): Transfer->__get()
#2 /opt/filesender/filesender/templates/transfers_table.php(246): Transfer->__get()
#3 /opt/filesender/filesender/classes/utils/Template.class.php(117): include('...')
#4 /opt/filesender/filesender/classes/utils/Template.class.php(124): Template::{closure}()
#5 /opt/filesender/filesender/classes/utils/Template.class.php(220): Template::process()
#6 /opt/filesender/filesender/templates/transfers_page.php(71): Template::display()
#7 /opt/filesender/filesender/classes/utils/Template.class.php(117): include('...')
#8 /opt/filesender/filesender/classes/utils/Template.class.php(124): Template::{closure}()
#9 /opt/filesender/filesender/classes/utils/Template.class.php(220): Template::process()
#10 /opt/filesender/filesender/templates/page.php(9): Template::display()
#11 /opt/filesender/filesender/classes/utils/Template.class.php(117): include('...')
#12 /opt/filesender/filesender/classes/utils/Template.class.php(124): Template::{closure}()
#13 /opt/filesender/filesender/classes/utils/Template.class.php(220): Template::process()
#14 /opt/filesender/filesender/www/index.php(92): Template::display()
#15 {main}
  thrown in /opt/filesender/filesender/classes/data/File.class.php on line 430
  ```

And I believe this is the error when calling from the rest client:

```  thrown in /opt/filesender/filesender/classes/data/File.class.php on line 430
[09-Apr-2024 07:51:34 Europe/London] PHP Warning:  Undefined array key 183 in /opt/filesender/filesender/classes/data/File.class.php on line 429
[09-Apr-2024 07:51:34 Europe/London] PHP Warning:  Attempt to read property "name" on null in /opt/filesender/filesender/classes/data/File.class.php on line 430
[09-Apr-2024 07:51:34 Europe/London] PHP Fatal error:  Uncaught Error: Attempt to assign property "pathCache" on null in /opt/filesender/filesender/classes/data/File.class.php:430
Stack trace:
#0 /opt/filesender/filesender/classes/data/Transfer.class.php(1084): File::fromTransfer()
#1 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(84): Transfer->__get()
#2 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(370): RestEndpointTransfer::cast()
#3 /opt/filesender/filesender/classes/rest/RestServer.class.php(299): RestEndpointTransfer->get()
#4 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
#5 {main}
```

May be wrong though.

**Comment by monkeyiq** [comment]
Thank you for the report. I have merged a fix (to 2.x) to stop this happening and also allow the UI to progress in the presence of stale data. I will port that forward to 3.x shortly.

**Comment by monkeyiq** [comment]
This is in yesterday's release. Thank you for the detailed report.
