### ISSUE TITLE
Uploading as logged in user does not work in 2.48/3.0beta7

### ISSUE THREAD

**Issue by moschlar** [filesender/filesender#1874]
The browser tries to do a POST request to `/filesender/rest.php/transfer` but that fails with error 500 and an empty response.

The server log shows no problems at all:

```
[2024-04-26 13:06:13] [user 54] [rest:info] Array
[2024-04-26 13:06:13] [user 54] [rest:info] (
[2024-04-26 13:06:13] [user 54] [rest:info]     [get_a_link] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [add_me_to_recipients] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_recipient_when_transfer_expires] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [hide_sender_email] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_me_copies] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_me_on_expire] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_upload_complete] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_download_complete] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_daily_statistics] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_report_on_closing] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [enable_recipient_email_download_complete] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [must_be_logged_in_to_download] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [encryption] =>
[2024-04-26 13:06:13] [user 54] [rest:info] )
[2024-04-26 13:06:13] [user 54] [rest:info]
[2024-04-26 13:06:13] [user 54] [rest:info] Array
[2024-04-26 13:06:13] [user 54] [rest:info] (
[2024-04-26 13:06:13] [user 54] [rest:info]     [get_a_link] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_recipient_when_transfer_expires] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [hide_sender_email] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_me_on_expire] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_upload_complete] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_download_complete] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_daily_statistics] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [email_report_on_closing] => 1
[2024-04-26 13:06:13] [user 54] [rest:info]     [must_be_logged_in_to_download] =>
[2024-04-26 13:06:13] [user 54] [rest:info]     [encryption] =>
[2024-04-26 13:06:13] [user 54] [rest:info] )
[2024-04-26 13:06:13] [user 54] [rest:info]
[2024-04-26 13:06:13] [user 54] [rest:info] File uid generation took 1 tries
[2024-04-26 13:06:13] [user 54] [rest:info] File#678(0.pdf, 440535 bytes) added to Transfer#295
[2024-04-26 13:06:13] [user 54] [rest:info] Recipient uid generation took 1 tries
[2024-04-26 13:06:13] [user 54] [rest:info] Recipient#306(anonymous) added to Transfer#295 with token c5bdda4d-952f-429a-9374-eb3c46f11279
[2024-04-26 13:06:13] [user 54] [rest:info] Event#transfer_started on Transfer#295
[2024-04-26 13:06:13] [user 54] [rest:info] Transfer#295 started
```

**Comment by moschlar** [comment]
Uh, I just found something in the syslog...

```
2024-04-26T13:06:13.892128+02:00 filesender-t-01 simplesamlphp[818]: PHP Fatal error:  Uncaught Error: Class "Locale" not found in /opt/filesender/filesender/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php
:44
2024-04-26T13:06:13.892763+02:00 filesender-t-01 simplesamlphp[818]: Stack trace:
2024-04-26T13:06:13.892867+02:00 filesender-t-01 simplesamlphp[818]: #0 /opt/filesender/filesender/classes/utils/Utilities.class.php(195): PHP81_BC\strftime()
2024-04-26T13:06:13.892934+02:00 filesender-t-01 simplesamlphp[818]: #1 /opt/filesender/filesender/classes/rest/RestUtilities.class.php(137): Utilities::formatDate()
2024-04-26T13:06:13.892996+02:00 filesender-t-01 simplesamlphp[818]: #2 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(71): RestUtilities::formatDate()
2024-04-26T13:06:13.893082+02:00 filesender-t-01 simplesamlphp[818]: #3 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(865): RestEndpointTransfer::cast()
2024-04-26T13:06:13.893150+02:00 filesender-t-01 simplesamlphp[818]: #4 /opt/filesender/filesender/classes/rest/RestServer.class.php(302): RestEndpointTransfer->post()
2024-04-26T13:06:13.893234+02:00 filesender-t-01 simplesamlphp[818]: #5 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
2024-04-26T13:06:13.893282+02:00 filesender-t-01 simplesamlphp[818]: #6 {main}
2024-04-26T13:06:13.893327+02:00 filesender-t-01 simplesamlphp[818]:   thrown in /opt/filesender/filesender/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php on line 44
```
and
```
2024-04-26T13:05:17.768262+02:00 filesender-t-01 simplesamlphp[242829]: PHP Fatal error:  Uncaught Error: Class "IntlDateFormatter" not found in /opt/filesender/filesender3/classes/utils/Utilities.class.php:185
2024-04-26T13:05:17.770039+02:00 filesender-t-01 simplesamlphp[242829]: Stack trace:
2024-04-26T13:05:17.770130+02:00 filesender-t-01 simplesamlphp[242829]: #0 /opt/filesender/filesender3/classes/rest/RestUtilities.class.php(137): Utilities::formatDate()
2024-04-26T13:05:17.770205+02:00 filesender-t-01 simplesamlphp[242829]: #1 /opt/filesender/filesender3/classes/rest/endpoints/RestEndpointTransfer.class.php(71): RestUtilities::formatDate()
2024-04-26T13:05:17.770275+02:00 filesender-t-01 simplesamlphp[242829]: #2 /opt/filesender/filesender3/classes/rest/endpoints/RestEndpointTransfer.class.php(874): RestEndpointTransfer::cast()
2024-04-26T13:05:17.770368+02:00 filesender-t-01 simplesamlphp[242829]: #3 /opt/filesender/filesender3/classes/rest/RestServer.class.php(302): RestEndpointTransfer->post()
2024-04-26T13:05:17.770441+02:00 filesender-t-01 simplesamlphp[242829]: #4 /opt/filesender/filesender3/www/rest.php(37): RestServer::process()
2024-04-26T13:05:17.770513+02:00 filesender-t-01 simplesamlphp[242829]: #5 {main}
2024-04-26T13:05:17.770583+02:00 filesender-t-01 simplesamlphp[242829]:   thrown in /opt/filesender/filesender3/classes/utils/Utilities.class.php on line 185
```

**Comment by monkeyiq** [comment]
This is part of the `strftime` being deprecated and the code having moved over to the more recommended date handling functions. Something likely got missed in the release notes here about minimal versions of php and extensions that may be now required to replace strftime.

I am on php-8.2.17 with the php-intl extension installed and enabled.

**Comment by moschlar** [comment]
Ah - yes - php-intl was not installed!
