### ISSUE TITLE
UI3: transfer log for file gives error

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#1884]
In the my transfer page looking up a files logs (See what happened to this file) always produces an error:

![image](https://github.com/filesender/filesender/assets/11512591/215e4f5c-e755-44e8-9b2f-148e466905a2)

logs:
```
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException exception uid:6632e558f2d52] transfer_not_found","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #0 \/filesender\/classes\/data\/DBObject.class.php(759): Transfer->__construct()","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #1 \/filesender\/classes\/data\/DBObject.class.php(191): DBObject::createFactory()","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #2 \/filesender\/classes\/rest\/endpoints\/RestEndpointTransfer.class.php(281): DBObject::fromId()","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #3 \/filesender\/classes\/rest\/RestServer.class.php(302): RestEndpointTransfer->get()","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #4 \/filesender\/www\/rest.php(37): RestServer::process()","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException trace uid:6632e558f2d52] #5 {main}","user":16,"time":1714611544}
{"app":"FileSender","process":"rest","level":"error","message":"[TransferNotFoundException details uid:6632e558f2d52] selector = \"id = 895\"","user":16,"time":1714611544}
```

It looks like the id is referring to a file not a transfer as running query: `select * from Files WHERE id=895` is the right file.

**Comment by monkeyiq** [comment]
Interesting. A good A/B is that it works in 2.x and not in 3.x.
