### ISSUE TITLE
PHP81_BC\strftime compatibility with PHP8.2

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1943]
While preparing an upgrade from filesender-2.40 to filesender-2.48, an issue seems to be introduced by the recently added PHP81_BC\strftime package:

A POST to the `rest.php/transfer` endpoint to create a transfer fails with:

```
PHP Fatal error:  Uncaught Error: Class "Locale" not found in /opt/filesender/filesender/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php:44
Stack trace:
#0 /opt/filesender/filesender/classes/utils/Utilities.class.php(195): PHP81_BC\strftime()
#1 /opt/filesender/filesender/classes/rest/RestUtilities.class.php(137): Utilities::formatDate()
#2 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(71): RestUtilities::formatDate()
#3 /opt/filesender/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(865): RestEndpointTransfer::cast()
#4 /opt/filesender/filesender/classes/rest/RestServer.class.php(302): RestEndpointTransfer->post()
#5 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
#6 {main}
  thrown in /opt/filesender/filesender/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php on line 44
  ```
With a subtle hint in the filesender debug logs:

```
[2024-06-25 11:42:00] [user 194781] [rest:info] Event#transfer_started on Transfer#1234568363
[2024-06-25 11:42:00] [user 194781] [rest:info] Transfer#1234568363 started
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:411 Lang::loadDictionary(string(nl_NL)) nl_NL
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:411 Lang::loadDictionary(string(nl_NL)) /opt/filesender/filesender/language/nl_NL
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:411 Lang::loadDictionary(string(nl_NL)) /opt/filesender/filesender/config/language/nl_NL
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:422 Lang::loadDictionary(string(en_AU)) en_AU
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:422 Lang::loadDictionary(string(en_AU)) /opt/filesender/filesender/language/en_AU
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/utils/Lang.class.php:422 Lang::loadDictionary(string(en_AU)) /opt/filesender/filesender/config/language/en_AU
[2024-06-25 11:42:00] [rest:debug] /opt/filesender/filesender/classes/autoload.php:193 Autoloader::load(string(Locale)) Looking for class Locale, expecting it at /opt/filesender/filesender/classes/utils/Locale.class.php but nothing found, may (or may not) be a problem ...
```

Environment:
OS: Rocky Linux 9.3
Webserver: `httpd-2.4.57-5.el9.x86_64`
PHP: `php-fpm-8.2.15-1.el9.remi.x86_64`

When downgrading everything back to 2.40,the POST call works again.

**Comment by WebSpider** [comment]
Ah. Missed the dependency to php-intl.

For future reference and searchengines: Install the `php-intl` module, restart php and webserver, and all will be fine.

**Comment by peter-** [comment]
While #1934 was merged two weeks ago it's not yet included in any release nor in the release candidate that came out today.

**Comment by monkeyiq** [comment]
That was merged into development3 and is at https://github.com/filesender/filesender/blob/c35b301ee15e022e784ea02f4f3d1fb1823cf28f/docs/v2.0/install/index.md?plain=1#L59

I think the v2.0 docs tree copy to v3.0 didn't include it in the v3.0 duplicate as yet. I had been trying to hold off making a v3.0 tree to avoid yet more duplication of source code but there was recently another push to get a docs tree duplication so now we have both v2.0 and v3.0 in the docs and the joy of maintaining that. I will port your patch over to the v3.0 docs now.

The PR was also against `development3` which as the above link shows is in master3 but in the v2.0 docs tree. I think the docs on the website comes form `master` which is crude patched form `development` so I will have to cherry pick that patch back to `development` for it to eventually appear in the docs on the website. 

I am not a fan of having 4 active branches but the m/d/m3/d3 setup is what the filesender board wishes so that is what is.

**Comment by monkeyiq** [comment]
I have that in the v3.0 tree of development3 now at https://github.com/filesender/filesender/pull/1949

**Comment by monkeyiq** [comment]
And this is picked back to docs/v2.0 as well now with https://github.com/filesender/filesender/pull/1950
