### ISSUE TITLE
[FileSender 2.49] PHP Fatal error on rest transfer

### ISSUE THREAD

**Issue by ringmeister84** [filesender/filesender#2027]
Hello, I am experiencing an error using FileSender 2.49 on PHP 8.2.13/RHEL9.
When trasfering files via remote application authentication, the POST on /rest.php/transfer fails with 500 error code, the php log says:
```
[02-Oct-2024 09:32:22 Europe/Rome] PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /usr/local/data/sites/fsender/filesender-filesender-2.49/classes/rest/endpoints/RestEndpointTransfer.class.php:564
Stack trace:
#0 /usr/local/data/sites/fsender/filesender-filesender-2.49/classes/rest/endpoints/RestEndpointTransfer.class.php(564): method_exists()
#1 /usr/local/data/sites/fsender/filesender-filesender-2.49/classes/rest/RestServer.class.php(302): RestEndpointTransfer->post()
#2 /usr/local/data/sites/fsender/filesender-filesender-2.49/www/rest.php(37): RestServer::process()
#3 {main}
  thrown in /usr/local/data/sites/fsender/filesender-filesender-2.49/classes/rest/endpoints/RestEndpointTransfer.class.php on line 564
```
The request body is as showed in the [rest doc](https://docs.filesender.org/filesender/v2.0/rest/).
Any idea? Thanks.

**Comment by WebSpider** [comment]
Anything in the filesender application log?

**Comment by WebSpider** [comment]
Feel free to submit it as a PR, so we can have a look at it.
Great to hear your problem is solved👍
