### ISSUE TITLE
S3 upload not working

### ISSUE THREAD

**Issue by hegedussz** [filesender/filesender#2066]
FileSender version: 2.40
S3: MinIO

Related configuration settings:

```
$config['storage_type'] = 'CloudS3';
$config['cloud_s3_endpoint'] = 'https://custom-minio-endpoint';
$config['cloud_s3_use_path_style_endpoint'] = true;
$config['cloud_s3_bucket'] = 'filesender-dev';
$config['cloud_s3_key']      = 'filesender-dev';
$config['cloud_s3_region'] = 'central-1';
$config['cloud_s3_secret']   = 'xxxx';
$config['cloud_s3_bucket_prefix'] = 'filesender-dev';
$config['cloud_s3_use_daily_bucket'] = true;
```

When I try to upload a file I get the following error:

```
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException exception uid:672a1b20be658] config_missing_parameter
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #0 /opt/filesender/filesender-filesender-2.50/classes/storage/StorageCloudS3.class.php(63): ConfigPrivate::get()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #1 /opt/filesender/filesender-filesender-2.50/classes/storage/StorageCloudS3.class.php(176): StorageCloudS3::getClient()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #2 /opt/filesender/filesender-filesender-2.50/classes/storage/Storage.class.php(207): StorageCloudS3::writeChunk()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #3 /opt/filesender/filesender-filesender-2.50/classes/data/File.class.php(452): Storage::writeChunk()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #4 /opt/filesender/filesender-filesender-2.50/classes/rest/endpoints/RestEndpointFile.class.php(531): File->writeChunk()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #5 /opt/filesender/filesender-filesender-2.50/classes/rest/RestServer.class.php(302): RestEndpointFile->put()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #6 /opt/filesender/filesender-filesender-2.50/www/rest.php(37): RestServer::process()
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException trace uid:672a1b20be658] #7 {main}
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException details uid:672a1b20be658] parameter = "cloud_s3_key"
[2024-11-05 14:18:24] [rest:error] [ConfigMissingParameterException details uid:672a1b20be658] noteToAdmin = ""
[2024-11-05 14:18:24] [user 15] [rest:info] S3: writeChunk() Can not write to object_name: 04d10f05-f946-4829-bc65-d32dde865bf0/000000000000000000000000 offset 0
[2024-11-05 14:18:24] [user 15] [rest:error] NOTE: MISSING PARAMETER IN CONFIG FILE
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException exception uid:672a1b20be809] storage_filesystem_cannot_write
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #0 /opt/filesender/filesender-filesender-2.50/classes/storage/Storage.class.php(207): StorageCloudS3::writeChunk()
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #1 /opt/filesender/filesender-filesender-2.50/classes/data/File.class.php(452): Storage::writeChunk()
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #2 /opt/filesender/filesender-filesender-2.50/classes/rest/endpoints/RestEndpointFile.class.php(531): File->writeChunk()
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #3 /opt/filesender/filesender-filesender-2.50/classes/rest/RestServer.class.php(302): RestEndpointFile->put()
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #4 /opt/filesender/filesender-filesender-2.50/www/rest.php(37): RestServer::process()
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException trace uid:672a1b20be809] #5 {main}
[2024-11-05 14:18:24] [user 15] [rest:error] [StorageFilesystemCannotWriteException details uid:672a1b20be809] path = "S3: writeChunk() Can not write to object_name: 04d10f05-f946-4829-bc65-d32dde865bf0/000000000000000000000000 offset 0  NOTE: MISSING PARAMETER IN CONFIG FILE"
```

**Comment by WebSpider** [comment]
You need to start using `config_private.php`. Have a look at your `config` dir

**Comment by hegedussz** [comment]
Thank you for the information. It works now.
