### ISSUE TITLE
Filesender does not provide a link when sending a file

### ISSUE THREAD

**Issue by symon33** [filesender/filesender#2067]
Hi team,

I kindly seeking for your help since I have set up filesender with my idp and it connect well but when I login to the filesender I'm unable to send the file or even get a link to be shared to a sender. Kindly help.

The below is screenshot of what is seen when sending a file.
![filesender](https://github.com/user-attachments/assets/34296127-0340-4d76-a9be-1f6d1d2e56c7)

**Comment by monkeyiq** [comment]
Is there anything in your log file? See the config settings like `log_facilities` to make sure you are logging at `debug` level.

I assume the apache user can write to `/opt/filesender/files/`

I have seen a stall at zero issue if my user can not read the file I am uploading (probably not the issue but thought I'd mention it).

Also take a look at the web console to see if there is anything that might shine some light here.

**Comment by symon33** [comment]
Hi Monkeyiq, 

Thank you for your response, I'm sharing the logs so you can help me to understand 
Also the /opt/filesender/files/ showing 
drwxr-x---  2 www-data root 4096 Aug 20 14:30 ./
drwxr-xr-x 24 root     root 4096 Aug 20 14:30 ../

The logs are showing the following 

[2024-11-01 03:35:48] [gui:error] [GUIUnknownPageException exception uid:67244c94ad8bc] unknown_page
[2024-11-01 03:35:48] [gui:error] [GUIUnknownPageException trace uid:67244c94ad8bc] #0 /opt/filesender/www/index.php(59): GUI::currentPage()
[2024-11-01 03:35:48] [gui:error] [GUIUnknownPageException trace uid:67244c94ad8bc] #1 {main}
[2024-11-01 03:35:48] [gui:error] [GUIUnknownPageException details uid:67244c94ad8bc] page = "/index/\think\app/invokefunction"
[2024-11-01 03:57:05] [gui:error] [DetailedException exception uid:67245191eacb5] exception_not_found
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #0 /opt/filesender/classes/utils/Template.class.php(123): include()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #1 /opt/filesender/classes/utils/Template.class.php(130): Template::{closure}()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #2 /opt/filesender/classes/utils/Template.class.php(258): Template::process()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #3 /opt/filesender/templates/page.php(9): Template::display()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #4 /opt/filesender/classes/utils/Template.class.php(123): include('...')
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #5 /opt/filesender/classes/utils/Template.class.php(130): Template::{closure}()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #6 /opt/filesender/classes/utils/Template.class.php(258): Template::process()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #7 /opt/filesender/www/index.php(92): Template::display()
[2024-11-01 03:57:05] [gui:error] [DetailedException trace uid:67245191eacb5] #8 {main}
[2024-11-01 03:57:05] [gui:warn] No translation found for exception_not_found in en language
[2024-11-01 03:57:05] [gui:error] translate() can not find translation for id exception_not_found
