### ISSUE TITLE
1071 Specified key was too long when updating UserPreferences key

### ISSUE THREAD

**Issue by thijskh** [filesender/filesender#25]
Hi,

When running the database upgrade on current master, I get a MySQL error "1071 Specified key was too long; max key length is 767 bytes" (see below). This is correct since the update tries to enlarge the id column from varchar(128) to varchar(255). Since for encoding reasons this requires up to 4 bytes per character, the requested size is 1020 bytes which oversteps InnoDB's prefix length for a primary key.

I wonder what the reason is for extending this column and if it's the best idea to have a primary id be a very long varchar that's hard to index? Perhaps use a numeric auto_increment id instead?

```
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException exception uid:58a456c7e6cd7] database_access_failure
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException trace uid:58a456c7e6cd7] #0 /srv/filesender/classes/utils/DatabaseMysql.class.php(245): DBI::__callStatic('exec', Array)
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException trace uid:58a456c7e6cd7] #1 /srv/filesender/classes/utils/Database.class.php(123): DatabaseMysql::updateTableColumnFormat('UserPreferences', 'id', Array, Array)
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException trace uid:58a456c7e6cd7] #2 /srv/filesender/scripts/upgrade/database.php(97): Database::updateTableColumnFormat('UserPreferences', 'id', Array, Array)
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException trace uid:58a456c7e6cd7] #3 {main}
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7] "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes"
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7] Array
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7] (
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]     [name] => exec
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]     [args] => Array
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]         (
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]             [0] => ALTER TABLE UserPreferences MODIFY id VARCHAR(255) NOT NULL PRIMARY KEY
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]         )
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7] )
[2017-02-15 13:25:27] [upgrade:error] [DBIUsageException details uid:58a456c7e6cd7]
```

**Comment by monkeyiq** [comment]
I can replicate this issue with explicit character set stipulation. Interestingly the 255 length works with utf8 because of the more compact storage which might be why it didn't hit everybody.

```
MariaDB [ben]> create table t6 ( id varchar(128) primary key ) character set utf32;
Query OK, 0 rows affected (0.27 sec)

MariaDB [ben]> create table t7 ( id varchar(255) primary key ) character set utf32;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

MariaDB [ben]> create table t8 ( id varchar(255) primary key ) character set utf8;
Query OK, 0 rows affected (0.28 sec)
```

I will be putting a fix in place in the next week or so.

**Comment by monkeyiq** [comment]
ok, so it seems that this issue will hit a column regardless of if it is the primary index or a secondary. The id is the email address (or login name) so will likely need to be indexed because FileSender will be looking up the table based on that key most of the time. So leaving it as the primary key for now is probably ok. Unless other tables start referencing into the UserPreferences table.

Trying to get around this using email as a secondary index:

```
MariaDB [ben]> create table t11 ( id int primary key, email varchar(190) unique ) character set utf32;
Query OK, 0 rows affected (0.31 sec)
MariaDB [ben]> create table t12 ( id int primary key, email varchar(195) unique ) character set utf32;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

There is the option of creating a prefix index on the first 190 character points only, which for <= 4 byte encodings is under the 767 byte limit. But I think in this case maybe just reducing the column to 190 characters is the more effective option. 

As a side note, I got away with the 255 byte utf8 primary key above by accident. In a later MariaDB I think the above t8 table creation would fail as utf8 can be up to 4 bytes per char https://en.wikipedia.org/wiki/UTF-8#Description.

**Comment by monkeyiq** [comment]
@thijskh hopefully the above merge fixes the issue for you
