### ISSUE TITLE
cron.php breaks on html code in transfer_expired.mail.php

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#301]
We noticed that our cron job exited with an error when deleting the expired files. Apparently it breaks on our modified transfer_expired.mail.php file which we had modified to send out a HTML mail, using code like <table style="w...'>.

As soon as we cleaned up the code and removed all HTML tags, it was working again.
Can we make this job more robust and make it less dependent on a failure by transfer_expired.mail.php?

In fact I would be happy also if there is an option not to send users a message if their transfer is expired...

A piece of the filesender log:
```
[2018-04-30 20:22:49] [cron:info] Cron started
[2018-04-30 20:22:51] [cron:info] Transfer#171 expired, closing it
[2018-04-30 20:22:51] [cron:info] Event#transfer_expired on Transfer#171
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException exception uid:xxx] no_such_property
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #0 /usr/share/filesender/filesender-2.0/classes/utils/Lang.class.php(685): Transfer->__get('d')
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #1 /usr/share/filesender/filesender-2.0/classes/utils/Lang.class.php(863): Translation->{closure}('transfer.d')
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #2 [internal function]: Translation->{closure}(Array)
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #3 /usr/share/filesender/filesender-2.0/classes/utils/Lang.class.php(874): preg_replace_callback('`\{(([^:\}]+:)?...', Object(Closure), '<table style="w...')
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #4 [internal function]: Translation->replace(Object(Recipient), Object(Transfer))
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #5 /usr/share/filesender/filesender-2.0/classes/utils/Lang.class.php(643): call_user_func_array(Array, Array)
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #6 [internal function]: Translation->replace(Object(Recipient), Object(Transfer))
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #7 /usr/share/filesender/filesender-2.0/classes/data/TranslatableEmail.class.php(243): call_user_func_array(Array, Array)
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #8 [internal function]: TranslatableEmail::prepare('transfer_expire...', Object(Recipient), Object(Transfer))
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #9 /usr/share/filesender/filesender-2.0/classes/data/Transfer.class.php(1128): call_user_func_array('TranslatableEma...', Array)
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #10 /usr/share/filesender/filesender-2.0/classes/data/Transfer.class.php(417): Transfer->sendToRecipient('transfer_expire...', Object(Recipient))
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #11 /usr/share/filesender/filesender-2.0/scripts/task/cron.php(58): Transfer->close(false)
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException trace uid:xxx] #12 {main}
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException details uid:xxx] class = "Transfer"
[2018-04-30 20:22:51] [cron:error] [PropertyAccessException details uid:xxx] property = “d"

```

**Comment by yent** [comment]
(as talked about during the 2018-05-01 workshop) This does not append because of the html markup but because there is something like `{transfer.d}` (probably typo of `{trandfer.id}`).

Anyway the application should be more robust against translation/template/theme bugs, probably by wrapping related parsing/evals in try-catches

**Comment by fransward** [comment]
Sweet! Type of trandfer.id indeed.

**Comment by monkeyiq** [comment]
Making it resilient to these issues, and also logging them instead of choking on them is a great plan. Too easy to make a typo in the template for that to bring the ship down.

**Comment by monkeyiq** [comment]
The above fixes a bad property for example: transfer.sizeee and already transferrrr.size was ok.
