### ISSUE TITLE
changing can_only_send_to_me to unavailable breaks guest vouchers

### ISSUE THREAD

**Issue by Erik-Horn** [filesender/filesender#460]
Setting the transfer option can_only_send_to_me to available=false and default=true causes guest uploads to fail with a transfer_no_recipients exception. Changing it to available=true and checking the box in the voucher request page does work.

When the guest accesses filesender using the voucher generated with can_only_send_to_me available=false, the correct recipient is shown on the screen correctly. So it appears that it is getting lost somewhere.

Thanks,

Erik

My transfer and guest options:

$config['transfer_options'] = array(
        'email_me_copies' => array( "available" => false, "advanced" => false, "default" => false  ),
        'email_me_on_expire' => array( "available" => true, "advanced" => false, "default" => false  ),
        'email_upload_complete' => array( "available" => false, "advanced" => false, "default" => false  ),
        'email_download_complete' => array( "available" => true, "advanced" => false, "default" => false  ),
        'email_daily_statistics' => array( "available" => false, "advanced" => false, "default" => false  ),
        'email_report_on_closing' => array( "available" => true, "advanced" => false, "default" => false  ),
        'enable_recipient_email_download_complete' => array( "available" => false, "advanced" => false, "default" => false  ),
        'add_me_to_recipients' => array( "available" => false, "advanced" => false, "default" => false  ),
        'get_a_link' => array( "available" => true, "advanced" => false, "default" => false  ),
        'redirect_url_on_complete' => array( "available" => false, "advanced" => false, "default" => false  ),
        );

$config['guest_options'] = array(
        'email_upload_started' => array( "available" => false, "advanced" => false, "default" => false ),
        'email_upload_page_access' => array( "available" => false, "advanced" => false, "default" => false  ),
        'valid_only_one_time' => array( "available" => true, "advanced" => false, "default" => true  ),
        'does_not_expire' => array( "available" => false, "advanced" => false, "default" => false  ),
        'can_only_send_to_me' => array( "available" => false, "advanced" => true, "default" => true  ),
        'email_guest_created' => array( "available" => true, "advanced" => false, "default" => true  ),
        'email_guest_created_receipt' => array( "available" => true, "advanced" => false, "default" => false  ),
        'email_guest_expired' => array( "available" => false, "advanced" => false, "default" => false  ),
        );

Filesender log:

[2019-01-09 09:43:24] [user 1] [rest:info] Array
[2019-01-09 09:43:24] [user 1] [rest:info] (
[2019-01-09 09:43:24] [user 1] [rest:info]     [get_a_link] =>
[2019-01-09 09:43:24] [user 1] [rest:info]     [add_me_to_recipients] =>
[2019-01-09 09:43:24] [user 1] [rest:info]     [email_me_on_expire] =>
[2019-01-09 09:43:24] [user 1] [rest:info]     [email_download_complete] =>
[2019-01-09 09:43:24] [user 1] [rest:info]     [email_report_on_closing] =>
[2019-01-09 09:43:24] [user 1] [rest:info]     [encryption] =>
[2019-01-09 09:43:24] [user 1] [rest:info] )
[2019-01-09 09:43:24] [user 1] [rest:info]
[2019-01-09 09:43:24] [user 1] [rest:error] [TransferNoRecipientsException exception uid:5c3632bc0aaef] transfer_no_recipients
[2019-01-09 09:43:24] [user 1] [rest:error] [TransferNoRecipientsException trace uid:5c3632bc0aaef] #0 [internal function]: RestEndpointTransfer->post()
[2019-01-09 09:43:24] [user 1] [rest:error] [TransferNoRecipientsException trace uid:5c3632bc0aaef] #1 /opt/filesender/filesender/classes/rest/RestServer.class.php(300): call_user_func_array(Array, Array)
[2019-01-09 09:43:24] [user 1] [rest:error] [TransferNoRecipientsException trace uid:5c3632bc0aaef] #2 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
[2019-01-09 09:43:24] [user 1] [rest:error] [TransferNoRecipientsException trace uid:5c3632bc0aaef] #3 {main}

**Comment by peter-** [comment]
May be related to [#439](https://github.com/filesender/filesender/issues/439#issuecomment-444565604) where I reported that:

> **All** `transfer_options` and `guest_options` that have been set in `config.php` to be `default => true` AND `available => false` (i.e., they're _active_ and _not shown_ to the subject in the web UI) are currently being silently ignored, as if they had not been set `default => true` at all.

**Comment by monkeyiq** [comment]
I think the way the options are presented can cause some confusion. Although the docs do go into things to help clarify. It might be simpler to understand if "available" was more verbose, perhaps "user_can_adjust". I have been thinking for some time that the way these "options" in both the guests and transfer tables are handled could be better served by a clean class abstraction with matching database setup for both. Though I digress. It has been useful fixing these options issues to get a cleaner impression of where things can be improved in the future.
