### ISSUE TITLE
cron.php crashed during it's execution

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#574]
The cause seems to be the data for 'variables' (> than 70 000 characters) is too long for the insert "INSERT INTO TranslatableEmails(context_type, context_id, token, translation_id, variables, created) VALUES(:context_type, :context_id, :token, :translation_id, :variables, :created)". 

This error may cause some transfers not expiring properly and files not being deleted from the server.

Quick hotfix: 
- throw an exception to catch the error
- log that the insert into the DB of the transfer data failed and the email was not sent
- cron.php continue its execution. 

FileSender version: 2.5

Error message from the cron.php:
```
PHP Notice:  Trying to get property 'lang' of non-object in /opt/filesender/classes/utils/Lang.class.php on line 190
PHP Fatal error:  Uncaught DBIUsageException: database_access_failure in /opt/filesender/classes/utils/DBI.class.php:367
Stack trace:
#0 /opt/filesender/classes/data/DBObject.class.php(624): DBIStatement->__call('execute', Array)
#1 /opt/filesender/classes/data/DBObject.class.php(363): DBObject::insertRecord(Array)
#2 /opt/filesender/classes/data/TranslatableEmail.class.php(219): DBObject->save()
#3 /opt/filesender/classes/data/TranslatableEmail.class.php(292): TranslatableEmail::create(Object(Transfer), 'report_inline', Array)
#4 /opt/filesender/classes/utils/Report.class.php(187): TranslatableEmail::prepare('report_inline', 'xxx.yyyy@zzzz...', Object(Transfer), Array)
#5 /opt/filesender/classes/data/Transfer.class.php(535): Report->sendTo(Object(User))
#6 /opt/filesender/scripts/task/cron.php(65): Transfer->close(false)
#7 {main}
  thrown in /opt/filesender/classes/utils/DBI.class.php on line 367
```

Error from the log:
```
[2019-06-11 06:26:30] [cron:error] [DBIUsageException exception uid:5cff2d76d2334] database_access_failure
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #0 /opt/filesender/classes/data/DBObject.class.php(624): DBIStatement->__call('execute', Array)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #1 /opt/filesender/classes/data/DBObject.class.php(363): DBObject::insertRecord(Array)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #2 /opt/filesender/classes/data/TranslatableEmail.class.php(219): DBObject->save()
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #3 /opt/filesender/classes/data/TranslatableEmail.class.php(292): TranslatableEmail::create(Object(Transfer), 'report_inline', Array)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #4 /opt/filesender/classes/utils/Report.class.php(187): TranslatableEmail::prepare('report_inline', 'xx.yy@zzzz...', Object(Transfer), Array)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #5 /opt/filesender/classes/data/Transfer.class.php(535): Report->sendTo(Object(User))
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #6 /opt/filesender/scripts/task/cron.php(65): Transfer->close(false)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException trace uid:5cff2d76d2334] #7 {main}
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334] "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'variables' at row 1"
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334] Array
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334] (
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]     [method] => execute
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]     [args] => Array
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]         (
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]             [0] => Array
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                 (
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:context_type] => Transfer
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:context_id] => 00000
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:token] => aaaaaaa
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:translation_id] => report_inline
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:variables] => [{"dbobject_type":"User","dbobject_id":1111},{"dbobject_type":"Transfer","dbobject_id":111},{"target":{"type":"Transfer","id":0000},"content":{"plain":"Date                 Action that happened\n\n03\/06\/2019 11:27:12  Transfer was created\n       anonymized: about 70079 characters              <td>Transfer expired<\/td><td><\/td><\/tr>"}}]
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                     [:created] => 2019-06-11 06:26:30
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]                 )
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]         )
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]     [query] => INSERT INTO TranslatableEmails(context_type, context_id, token, translation_id, variables, created) VALUES(:context_type, :context_id, :token, :translation_id, :variables, :created)
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334] )
[2019-06-11 06:26:30] [cron:error] [DBIUsageException details uid:5cff2d76d2334]
```

**Comment by monkeyiq** [comment]
If the mediumtext update doesn't fully resolve things for anyone, please reopen.
