### ISSUE TITLE
"Delete all my data" broken

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#665]
Running the latest tag `2.9` I get this error in the log (and an HTTP 500 code for the `DELETE /rest.php/user/@me` request) when trying to "delete all my data" using the eponymous button in the "My profile" page:

```
PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Transfer::fromGuestsOf(),
1 passed in /opt/filesender/classes/data/User.class.php on line 671 and exactly
2 expected in /opt/filesender/classes/data/Transfer.class.php:341
Stack trace:
#0 /opt/filesender/classes/data/User.class.php(671): Transfer::fromGuestsOf(Object(User))
#1 /opt/filesender/classes/data/DBObject.class.php(413): User->beforeDelete()                       
#2 /opt/filesender/classes/rest/endpoints/RestEndpointUser.class.php(325): DBObject->delete()       
#3 /opt/filesender/classes/rest/RestServer.class.php(303): RestEndpointUser->delete('@me')                          
#4 /opt/filesender/www/rest.php(37): RestServer::process()                                          
#5 {main}
  thrown in /opt/filesender/classes/data/Transfer.class.php on line 341
```

This is using PostgreSQL 11.5 and PHP 7.3 both as provided by Debian 10 (current `stable`).

**Comment by peter-** [comment]
Duplicated #658, sorry (local `master` was out of date).
