### ISSUE TITLE
Sometimes chunk sizes are too small

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#78]
I'm getting reports of FileSender failing with an error code. After lookup, these error codes represent error messages such as:

```
[rest:error] [RestSanityCheckFailedException details uid:xxxxxxxxxxxxx] "check "chunk_size", "5242880" value was expected but got "5111808" instead"
```
```
[rest:error] [RestSanityCheckFailedException details uid:xxxxxxxxxxxxx] "check "chunk_size", "5242880" value was expected but got "4964149" instead"
```

Reportedly, this error does not occur when the user disables TeraSender. The file uploaded is typically a .ZIP file and the crypto module is not used.

**Comment by jornane** [comment]
We have getting reports of this happening in IE, Chrome and Safari.

**Comment by monkeyiq** [comment]
I assume that this is still popping up from time to time.

Could you please share the terrasender config you are using that might differ from the defaults below. It seems from the above log that you are on the default chunk size of 5242880 (5 by 1k by 1k).

```
    'upload_chunk_size' => 5 * 1024 * 1024,
    'chunk_upload_security' => 'key',
    'download_chunk_size' => 5 * 1024 * 1024,

    'terasender_enabled' => true,
    'terasender_disableable' => true,
    'terasender_start_mode' => 'multiple',
    'terasender_worker_count' => 6,
    'stalling_detection' => false,
```

**Comment by monkeyiq** [comment]
I'm still trying to reproduce this. Using chrome and safari so far on mac and win10.

I made pr 132 which will pickup the file name, sizes, and browser version in the server logs. It would be great if somebody is willing to run that to try to see if we can narrow down what is triggering this so I can reproduce it and remove it.

https://github.com/filesender/filesender/pull/132

**Comment by jornane** [comment]
```
$config['terasender_enabled'] = false;
$config['terasender_worker_count'] = 5;
$config['terasender_start_mode'] = "single";
$config['stalling_detection'] = false;
```

However I've had TeraSender disabled for a while now, and haven't had any complaints since.

**Comment by monkeyiq** [comment]
I'll do some more testing in start_mode = single tomorrow.

**Comment by monkeyiq** [comment]
I am testing with git version 34bb9d6e955be65d3a930a0d5ea38d0442fb570c which is branched from master at 2244a11bd536c1780e6b619471085d5570727bb8. The only thing that 34bb9d6e955be65d3a930a0d5ea38d0442fb570c adds in is more verbose log messages if the chunk_size error is thrown.

I have set the settings from the post above (replicated below) and use the default chunk size
```
$config['terasender_enabled'] = true;
$config['terasender_worker_count'] = 5;
$config['terasender_start_mode'] = "single";
$config['stalling_detection'] = false;
```

The dataset contains 4 zip files, as these were cited as the issue file above.
684 bytes - small.zip contains 3 files which are the output of date > file1
5.7 mb - AAA.zip contains 80 non English utf8 text files from project gutenburg (manifest below)
15mb - AAA-nc.zip is the above but with -n txt to only store the text instead of compressing it.
45 mb - big.zip contains 8 copies of AAA.zip 

I upload each zip about 10 times and then all 4 in a single upload 10 times.

I am testing using a Windows 10 machine and Macbook Air (running 10.12.5).

On OSX all uploads succeeded.
* Google Chrome Version 61.0.3163.91 (Official Build) (64-bit)
* Safari        Version 10.1.1 (12603.2.4)

Windows 10 all uploads succeeded.
* Google Chrome Version 61.0.3163.91 (Official Build) (64-bit)
* Microsoft Edge 40.15063.0.0 / Microsoft EdgeHTML 15.15063


AAA.zip manifest is about 20 copies of these four books which were chosen completely at random. I am unable to read them myself but chose a mixture of languages to try to test if utf8 encoding (thus AAA-nc) has anything to do with the issue.
```
   298929  10-10-2013 10:57   AAA/eurolang/43923-0.txt - Le lion du désert
   109957  09-20-2017 11:09   AAA/eurolang/pg15291.txt - Gildet På Solhaug
   170108  09-20-2017 11:07   AAA/eurolang/pg417.txt - The Hymns of Martin Luther
   191284  09-20-2017 11:08   AAA/eurolang/pg9046.txt - Koenig Ottokars Glueck und Ende Trauerspiel in fuenf Aufzuegen
```

**Comment by monkeyiq** [comment]
I'm not sure if this has been fixed between early June when it was reported. I can't manage to trigger it locally and am still trying to get some reports of it in the wild so I can try to reproduce it here. See https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2017-09/msg00016.html for info from the mailing list about checking if some of your users might be seeing the issue, and if so how you can collect slightly more info so that filename and browser id string are known in case specific versions of the later are needed in order to trigger the issue.

Given the above tests with the above browsers on multiple operating systems I am closing the issue here until somebody finds it in the wild.

**Comment by monkeyiq** [comment]
This has been reported as happening for Michael D'Silva. I will try to get more info to try to trigger it locally.

**Comment by jornane** [comment]
I've had a report from a user on Google Chrome who had the same problem. We have TeraSender disabled on our setup, so there goes the theory that this only happens when TeraSender is enabled.

**Comment by jornane** [comment]
Another report from a user on Internet Explorer, this time on a cabled connection.

**Comment by jornane** [comment]
Still no report of problems from Firefox users, though.

**Comment by monkeyiq** [comment]
It seems that TeraSender is working ok. I have done testing locally on multiple browsers, OS, and file loads and have been fortunate enough to test on a reasonable sized active installation.

For non TeraSender upload issues it would be great to enable the verbose logging and try to get some more info on what OS/Browser and file types might be most able to trigger the issue. This support is now in master and can get enabled for all logging exceptions with
```
$config['exception_additional_logging_regex'] = '.*Exception';
```
Or simply using `RestSanityCheckFailedException` as the match pattern to only enable the additional log for Rest exceptions. This generates up to 6 lines of log per failure, so shouldn't stall or clog things.

**Comment by monkeyiq** [comment]
Is there any time pattern to these? Thinking out loud maybe these are more likely if the server is under load than not. Though if they happen at fairly random times then perhaps load isn't a contributing factor.

**Comment by monkeyiq** [comment]
By introducing a major delay on the server I have managed to milk some chunk_size errors out of the server. Though this is not likely to match the situation you are describing because the client side doesn't show the error code for a sys admin to search with. At least I have one synthetic use case that will reliably generate these for terasender. My hope is to narrow down more closely a situation that will generate the errors and give the client side dialog with error code.

If anyone wants to make some chunk size errors I found adding the last 5 lines shown below to be effective:

```
classes/rest/endpoints/RestEndpointFile.class.php
put() ...
        if($mode == 'chunk') {
            // Need to put a chunk of data

            // hammer + thumb
            if( $offset > 1 ) {
                Logger::error('sleeping!');
                sleep(120);
            }
```

**Comment by WebSpider** [comment]
We are seeing this on a regular basis, and are now also seeing transfers where the chunks are only containing NULL (00) characters for some chunks.
I am working to see if the two are connected.

**Comment by madsi1m** [comment]
Also seeing this again, specifically "check "chunk_size", "12582912" value was expected but got "32768" instead"  or 0 or another random small number. (we are running 3.38)

**Comment by madsi1m** [comment]
This seems to be from one of our customers wifi, switching to a different wifi network seems to fix the issue. No idea at this stage what the wifi network/firewalls are doing to the chunks or why it only seems to affect filesender

**Comment by spgreen** [comment]
Sorry to revive this issue but seeing this appear on a new installation using FileSender 2.4.9 on Ubuntu 24.04 LTS with PHP 8.3 and Apache 2.4.58


Error uploading iso to FileSender

```
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException EXCEPT-REST-CHUNK-SIZE uid:66d5235a7cfed] file size:1630404608
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException EXCEPT-REST-CHUNK-SIZE uid:66d5235a7cfed] file name:TrueNAS-SCALE-24.04.2.iso
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException EXCEPT-REST-CHUNK-SIZE uid:66d5235a7cfed] file uid:f429e649-26c7-4a47-91fd-03227529b682
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException EXCEPT-REST-CHUNK-SIZE uid:66d5235a7cfed] chunk size:5242880
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException EXCEPT-REST-CHUNK-SIZE uid:66d5235a7cfed] user agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException exception uid:66d5235a7cfed] rest_sanity_check_failed
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException trace uid:66d5235a7cfed] #0 /opt/filesender/filesender/classes/rest/RestServer.class.php(302): RestEndpointFile->put()
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException trace uid:66d5235a7cfed] #1 /opt/filesender/filesender/www/rest.php(37): RestServer::process()
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException trace uid:66d5235a7cfed] #2 {main}
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException details uid:66d5235a7cfed] method = "put"
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException details uid:66d5235a7cfed] endpoint = "file"
[2024-09-02 10:30:50] [user 15] [rest:error] [RestSanityCheckFailedException details uid:66d5235a7cfed] "check "chunk_size", "5242880" value was expected but got "8192" instead"
```

All of the configuration directives are set to the defaults ie chunk size of 5MB.

Was there any resolution found during the previous times that this occurred?

**Comment by thuso607** [comment]
Hi @spgreen , were you able to find a solution to this problem? I still experience on my filesender deployment

**Comment by WebSpider** [comment]
I am very uncertain this is actually a problem, but rather an Exception that should not be.

In filesender, larger transfers are broken into chunks. These chunks have a fixed size (i think the default is 5MB).
It's only logical that the last chunk of a file will not be 5MB, since a file very rarely is exactly the chunksize.

In the instances of this exception that I have investigated, it's always the last chunk that is concerned, and the file arrives intact.

**Comment by thuso607** [comment]
The issue causes the file upload to stop. The issue occurs intermittently even on good network speed. I tried changing storage type from "filesystem" to "filesystemChunked" but it still persists. A significant amount of my users have reported it and I can't seem to get it resolved

**Comment by spgreen** [comment]
I was experiencing this when setting up FileSender on a container system.
Moving to a VM resolved the issue for me.

**Comment by fresh0domi** [comment]
i facing the same Problem.. 

`[rest:error] [RestSanityCheckFailedException details uid:68889b7b18bdc] "check "chunk_size", "5242880" value was expected but got "49152" instead"`

the terrasender options are default.. the funny thing is with default options the upload works with small files <2GB but as soon as i change the terrasender values i cannot upload anything anymore cause the erros appears instead.. and if i change the value back to default, the upload still dosnt work and i need to restore the backup.. that happens even i only change the the terrasender enabled option to false and back to true.. no upload possible..

tested it with Linux/Ubuntu/XFC Firefox and Windows10 Firefox/Chrome/Edge + different Networks and Clients everyware the same..

filesender 2.56 running on Ubuntu24 Apache and php8.3


bests
