### ISSUE TITLE
MySQL/MariaDB View's SELECT contains a subquery in the FROM clause for upgrade/database.php

### ISSUE THREAD

**Issue by bepstein** [filesender/filesender#830]
CentOS 7.8
New install of 2.19.
MariaDB 10.1.46

I'm getting the following error when trying to run the upgrade/database.php script on initial install.

[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException exception uid:5f4e4e8638759] database_access_failure
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException trace uid:5f4e4e8638759] #0 /opt/filesender/filesender/classes/utils/DatabaseMysql.class.php(86): DBI::__callStatic()
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException trace uid:5f4e4e8638759] #1 /opt/filesender/filesender/classes/utils/Database.class.php(178): DatabaseMysql::createView()
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException trace uid:5f4e4e8638759] #2 /opt/filesender/filesender/scripts/upgrade/database.php(605): Database::createView()
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException trace uid:5f4e4e8638759] #3 {main}
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759] "SQLSTATE[HY000]: General error: 1349 View's SELECT contains a subquery in the FROM clause"
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759] Array
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759] (
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]     [name] => exec
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]     [args] => Array
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]         (
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]             [0] => CREATE OR REPLACE VIEW transfersauditlogsdlcountview as select t.*,count from Transfers t  left outer join (select id,count(*) as count from transfersauditlogsview where   ( event = 'download_ended' or event = 'archive_download_ended' ) group by id) zz  on t.id = zz.id
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]         )
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759] )
[2020-09-01 14:37:10] [upgrade:error] [DBIUsageException details uid:5f4e4e8638759]

I'm seeing that MySQL 5.7.7 included support for this functionality, but I'm not sure when or if it was added to MariaDB.

Thanks,
ep

**Comment by bepstein** [comment]
I updated to MariaDB 10.5.5 and this script seems to be working fine now.

Thanks,
ep
