### ISSUE TITLE
Admin sorting transfers fails with "Unknown admin section"

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#889]
Regarding #745: When accessing the admin tab and clicking on the `Transfer ID` column head I get this error:

```
The application encountered an error while processing your request
  Unknown admin section
When reporting this error please give the following code to help the support finding out details : "5fce66ab69d42" 
```
![transfer-sort-by-id](https://user-images.githubusercontent.com/4047365/101388938-e4e4ac80-38c0-11eb-8059-67fe965853e5.png)

The log reports this for the given id:

```
[gui:error] [GUIUnknownAdminSectionException exception uid:5fce66ab69d42] gui_unknown_admin_section
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #0 /opt/filesender/classes/utils/Template.class.php(117): include()
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #1 /opt/filesender/classes/utils/Template.class.php(124): Template::{closure}('/opt/filesender...', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #2 /opt/filesender/classes/utils/Template.class.php(220): Template::process('admin_page', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #3 /opt/filesender/templates/page.php(9): Template::display('admin_page', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #4 /opt/filesender/classes/utils/Template.class.php(117): include('/opt/filesender...')
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #5 /opt/filesender/classes/utils/Template.class.php(124): Template::{closure}('/opt/filesender...', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #6 /opt/filesender/classes/utils/Template.class.php(220): Template::process('page', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #7 /opt/filesender/www/index.php(66): Template::display('page', Array)
[gui:error] [GUIUnknownAdminSectionException trace uid:5fce66ab69d42] #8 {main}
[gui:error] [GUIUnknownAdminSectionException details uid:5fce66ab69d42] section = ""
```
The column chosen doesn't seem to matter, the same error and code trace appears for other columns (Recipients, Size, Files, ...)

This is on a clean tag `master-filesender-2.20`. Not sure what I could be missing?

**Comment by peter-** [comment]
FWIW, sorting your own transfers as user works fine.

**Comment by monkeyiq** [comment]
Thank you for the detailed report. This should be fixed with https://github.com/filesender/filesender/pull/893 above. I was able to reproduce the issue before the fix and see it changed after.

**Comment by monkeyiq** [comment]
As this is a fix I could verify I am closing it as resolved with 893.
