### ISSUE TITLE
Rest Error After 2.22 Upgrade

### ISSUE THREAD

**Issue by drudich** [filesender/filesender#991]
We are getting the following errors in the FileSender log after upgrading to v2.22.  I also ran the database upgrade script and it completed successfully.

Any suggestions to get this working?  I have rolled back to the previous version in the meantime.

[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException exception uid:606ef7abaed89] cannot_add_data_to_complete_transfer
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException trace uid:606ef7abaed89] #0 /opt/filesender/classes/rest/RestServer.class.php(305): RestEndpoin
tFile->put('635', 'chunk')
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException trace uid:606ef7abaed89] #1 /opt/filesender/www/rest.php(37): RestServer::process()
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException trace uid:606ef7abaed89] #2 {main}
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException details uid:606ef7abaed89] method = "put"
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException details uid:606ef7abaed89] endpoint = "file"
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException details uid:606ef7abaed89] target_type = "File"
[2021-04-08 08:31:39] [user 16] [rest:error] [RestCannotAddDataToCompleteTransferException details uid:606ef7abaed89] target_id = 635

**Comment by monkeyiq** [comment]
Looking at the code it seems this exception should only be thrown if the upload has not started or is not still "uploading".

Does this happen every time? Is it at the start, end, middle, or any of those times during the upload? Which browser and perhaps server might also be useful to know.

**Comment by madsi1m** [comment]
I have seen something like this when I update the code and my browser still has the older js cached (but I am jumping from 2.9 to 2.22 so the differences in code is significant)

**Comment by drudich** [comment]
Yes, it happens every time... and the file that I am uploading is very small (under 1MB).  I've tried with different file types too and get the same error.  

I have been trying it in an incognito window, so cache shouldn't be an issue.

**Comment by drudich** [comment]
Just upgraded to 2.24 and getting the same error.

**Comment by monkeyiq** [comment]
So we know that v2.21 works ok for you but v2.22+ do not. 

This means the commit before v2.21 was released should be ok:
https://github.com/filesender/filesender/pull/898/commits/c906a5150423ab5dea87b9b52e13c9230d79e35f

But by the time the last commit goes in before v2.22 was released something has disrupted things for your setup
https://github.com/filesender/filesender/pull/935/commits/98c31d207ea60253bc05201506046b868fd56f6f

Maybe we could bisect the issue a little by looking at a commit in the middle?
https://github.com/filesender/filesender/pull/920/commits/dba93285e839fd05f7db393af524123bc8482812

```
git checkout dba93285e839fd05f7db393af524123bc8482812
test.
```

**Comment by drudich** [comment]
@monkeyiq  Sorry - I should have been more clear.  We upgraded from 2.18 to 2.22 so it's difficult to tell which commit is causing the problem.  Is there a way to enable debug logging within FileSender to get more info?

**Comment by drudich** [comment]
I enabled debug logging and I see the following in the logs:

[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException exception uid:60746da03076e] config_bad_parameter
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #0 /opt/filesender/classes/data/Transfer.class.php(1647): ApplicationMail->send()
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #1 /opt/filesender/classes/data/Transfer.class.php(1489): Transfer->sendToRecipient('transfer_availa...', Object
(Recipient))
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #2 /opt/filesender/classes/rest/endpoints/RestEndpointTransfer.class.php(840): Transfer->makeAvailable()
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #3 /opt/filesender/classes/rest/RestServer.class.php(305): RestEndpointTransfer->put('5')
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #4 /opt/filesender/www/rest.php(37): RestServer::process()
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException trace uid:60746da03076e] #5 {main}
[2021-04-12 11:56:16] [rest:error] [ConfigBadParameterException details uid:60746da03076e] parameter = "email_from"

**Comment by drudich** [comment]
I had an issue with the "email_from" field which I fixed... it's still having an issue though.  When I attempt to upload a file, it fails the first couple of times and then it completes.  This is what shows in the UI, when it fails the first couple of times:

![image](https://user-images.githubusercontent.com/39833704/114426440-14b20280-9b88-11eb-9f35-efb983150115.png)

Any suggestions?  I'm not seeing anything in the logs

**Comment by monkeyiq** [comment]
Most of the time if filesender-config.js.php has failed to load it means there is something in your config.php that is not being handled properly by filesender-config.js.php. You should be able to load https://yoursite/filesender/filesender-config.js.php directly in your browser. It should present valid JSON when you load it but if there is an issue it will break off at the end of file instead of closing properly. So the end of that config.js.php might give a clue as to where to start.

I keep adding more checks to filesender-config.js.php over time to try to handle such cases gracefully but it is a process.

**Comment by drudich** [comment]
Thank you @monkeyiq 

This is the only section of the file that does not show up when I access the URL for the file:

![image](https://user-images.githubusercontent.com/39833704/114572049-260d1480-9c45-11eb-871b-14c91617dd5e.png)

Any ideas?  Is this normal that this section is not showing in the browser?

**Comment by monkeyiq** [comment]
ok, so the config seems to be ok. You will not see that force_legacy_mode block unless you have force_legacy_mode=true in your config which is not likely these days.

To help narrow things from there could you test out 2.20 to try to narrow down which release started causing trouble for you?

**Comment by drudich** [comment]
I ended up just starting with a fresh installation of 2.24 and then copied my configuration back into it.  Everything appears to be working now.
